/**
 * Vraies séances du "Monde de Cléo CE1" (Retz, Antoine Fetet), sommaire officiel.
 * fichierPage = page du fichier élève (ce que l'élève ouvre en classe, ex. "p. 8"),
 * guidePage = page correspondante dans le guide pédagogique du maitre (ex. "p. 120").
 * Les deux sommaires listent les mêmes 71 séances dans le même ordre par période ;
 * ce fichier aligne les deux pages position par position.
 * Distinct de CLEO_CATALOG (ardoise-eval.ts), qui n'est qu'une sélection de points
 * d'évaluation et ne couvre pas toutes les séances.
 * Fichier séparé, mêmes conventions que storage.ts / timetable-storage.ts.
 */

export type CleoSeance = {
  id: string;
  period: 1 | 2 | 3 | 4 | 5;
  fichierPage: number;
  guidePage: number;
  title: string;
};

export const CLEO_SEANCES: CleoSeance[] = [
  // ── Période 1 ──────────────────────────────────────────────────────────
  {
    id: "cleo-p1-1",
    period: 1,
    fichierPage: 8,
    guidePage: 120,
    title: "Je comprends ce qui est « caché » dans un texte",
  },
  {
    id: "cleo-p1-2",
    period: 1,
    fichierPage: 9,
    guidePage: 125,
    title: "Je classe les mots dans l'ordre alphabétique",
  },
  {
    id: "cleo-p1-3",
    period: 1,
    fichierPage: 10,
    guidePage: 128,
    title: "Je découvre le singulier et le pluriel des noms",
  },
  {
    id: "cleo-p1-4",
    period: 1,
    fichierPage: 12,
    guidePage: 133,
    title: "J'écris les mots avec oi, ou, on",
  },
  {
    id: "cleo-p1-5",
    period: 1,
    fichierPage: 14,
    guidePage: 136,
    title: "Je comprends des phrases complexes",
  },
  {
    id: "cleo-p1-6",
    period: 1,
    fichierPage: 16,
    guidePage: 139,
    title: "Je découvre les familles de mots (1)",
  },
  {
    id: "cleo-p1-7",
    period: 1,
    fichierPage: 18,
    guidePage: 142,
    title: "J'écris les mots avec i/in, ai/ain",
  },
  {
    id: "cleo-p1-8",
    period: 1,
    fichierPage: 20,
    guidePage: 144,
    title: "J'accorde le verbe avec le sujet (1)",
  },
  {
    id: "cleo-p1-9",
    period: 1,
    fichierPage: 22,
    guidePage: 147,
    title: "J'écris les mots avec ar/ra, ir/ri, or/ro…",
  },
  {
    id: "cleo-p1-10",
    period: 1,
    fichierPage: 24,
    guidePage: 149,
    title: "J'associe des phrases et des images",
  },
  {
    id: "cleo-p1-11",
    period: 1,
    fichierPage: 26,
    guidePage: 153,
    title: "Je classe les noms en catégories",
  },
  {
    id: "cleo-p1-12",
    period: 1,
    fichierPage: 28,
    guidePage: 157,
    title: "Je découvre le passé, le présent et le futur",
  },
  {
    id: "cleo-p1-13",
    period: 1,
    fichierPage: 30,
    guidePage: 162,
    title: "J'écris les mots avec ai, an, au, eau",
  },

  // ── Période 2 ──────────────────────────────────────────────────────────
  {
    id: "cleo-p2-1",
    period: 2,
    fichierPage: 32,
    guidePage: 164,
    title: "Je choisis les bons déterminants",
  },
  {
    id: "cleo-p2-2",
    period: 2,
    fichierPage: 34,
    guidePage: 167,
    title: "J'écris les mots avec g ou gu",
  },
  {
    id: "cleo-p2-3",
    period: 2,
    fichierPage: 36,
    guidePage: 170,
    title: "Je fais attention à tous les détails de la phrase",
  },
  {
    id: "cleo-p2-4",
    period: 2,
    fichierPage: 38,
    guidePage: 174,
    title: "Je comprends des mots qui ont plusieurs sens",
  },
  {
    id: "cleo-p2-5",
    period: 2,
    fichierPage: 40,
    guidePage: 176,
    title: "J'accorde le verbe avec le sujet (2)",
  },
  {
    id: "cleo-p2-6",
    period: 2,
    fichierPage: 42,
    guidePage: 179,
    title: "J'écris les mots avec elle, ette, esse, enne, erre",
  },
  {
    id: "cleo-p2-7",
    period: 2,
    fichierPage: 44,
    guidePage: 182,
    title: "Je comprends où commence et où finit une phrase",
  },
  {
    id: "cleo-p2-8",
    period: 2,
    fichierPage: 46,
    guidePage: 187,
    title: "Je découvre les diminutifs",
  },
  {
    id: "cleo-p2-9",
    period: 2,
    fichierPage: 48,
    guidePage: 190,
    title: "Je reconnais le verbe et le nom (1)",
  },
  {
    id: "cleo-p2-10",
    period: 2,
    fichierPage: 50,
    guidePage: 194,
    title: "J'écris les mots avec s ou ss",
  },
  {
    id: "cleo-p2-11",
    period: 2,
    fichierPage: 52,
    guidePage: 197,
    title: "J'adapte ma lecture au fil du texte",
  },
  {
    id: "cleo-p2-12",
    period: 2,
    fichierPage: 56,
    guidePage: 200,
    title: "J'écris les mots avec rt, rp, rs, st, str…",
  },
  {
    id: "cleo-p2-13",
    period: 2,
    fichierPage: 58,
    guidePage: 202,
    title: "Je conjugue les verbes au présent avec il, elle ou ils, elles",
  },
  {
    id: "cleo-p2-14",
    period: 2,
    fichierPage: 60,
    guidePage: 207,
    title: "Je maitrise l'apostrophe et les liaisons",
  },

  // ── Période 3 ──────────────────────────────────────────────────────────
  {
    id: "cleo-p3-1",
    period: 3,
    fichierPage: 68,
    guidePage: 210,
    title: "Je trouve le sujet et le verbe de la phrase (1)",
  },
  {
    id: "cleo-p3-2",
    period: 3,
    fichierPage: 70,
    guidePage: 213,
    title: "Je forme des mots nouveaux",
  },
  {
    id: "cleo-p3-3",
    period: 3,
    fichierPage: 74,
    guidePage: 216,
    title: "Je découpe les mots en syllabes",
  },
  {
    id: "cleo-p3-4",
    period: 3,
    fichierPage: 76,
    guidePage: 221,
    title: "Je conjugue les verbes au présent avec nous et vous",
  },
  {
    id: "cleo-p3-5",
    period: 3,
    fichierPage: 78,
    guidePage: 224,
    title: "Je lis différents types de documents",
  },
  {
    id: "cleo-p3-6",
    period: 3,
    fichierPage: 82,
    guidePage: 226,
    title: "J'écris les mots avec c ou qu",
  },
  {
    id: "cleo-p3-7",
    period: 3,
    fichierPage: 84,
    guidePage: 228,
    title: "Je maitrise l'accent aigu (é)",
  },
  {
    id: "cleo-p3-8",
    period: 3,
    fichierPage: 86,
    guidePage: 232,
    title: "J'accorde l'adjectif avec le nom",
  },
  {
    id: "cleo-p3-9",
    period: 3,
    fichierPage: 88,
    guidePage: 236,
    title: "Je trouve le sens d'adjectifs inconnus",
  },
  {
    id: "cleo-p3-10",
    period: 3,
    fichierPage: 90,
    guidePage: 238,
    title: "J'écris les mots avec c ou ç",
  },
  {
    id: "cleo-p3-11",
    period: 3,
    fichierPage: 92,
    guidePage: 240,
    title: "Je conjugue les verbes être et avoir au présent",
  },
  {
    id: "cleo-p3-12",
    period: 3,
    fichierPage: 94,
    guidePage: 243,
    title: "Je conjugue les verbes au présent avec je et tu",
  },
  {
    id: "cleo-p3-13",
    period: 3,
    fichierPage: 98,
    guidePage: 245,
    title: "Je comprends de qui ou de quoi on parle",
  },
  {
    id: "cleo-p3-14",
    period: 3,
    fichierPage: 100,
    guidePage: 248,
    title: "J'écris des verbes au pluriel",
  },
  {
    id: "cleo-p3-15",
    period: 3,
    fichierPage: 102,
    guidePage: 250,
    title: "Je comprends le sens propre et le sens figuré",
  },

  // ── Période 4 ──────────────────────────────────────────────────────────
  {
    id: "cleo-p4-1",
    period: 4,
    fichierPage: 104,
    guidePage: 253,
    title: "Je connais les pronoms sujets",
  },
  {
    id: "cleo-p4-2",
    period: 4,
    fichierPage: 108,
    guidePage: 256,
    title: "Je conjugue les verbes au futur",
  },
  {
    id: "cleo-p4-3",
    period: 4,
    fichierPage: 110,
    guidePage: 259,
    title: "J'écris les mots avec g ou ge",
  },
  {
    id: "cleo-p4-4",
    period: 4,
    fichierPage: 114,
    guidePage: 262,
    title: "J'écris les mots avec in/ine, ain/aine, ein/eine, un/une",
  },
  {
    id: "cleo-p4-5",
    period: 4,
    fichierPage: 116,
    guidePage: 264,
    title: "Je reconnais le verbe et le nom (2)",
  },
  {
    id: "cleo-p4-6",
    period: 4,
    fichierPage: 118,
    guidePage: 266,
    title: "Je comprends dans quel ordre se passent les choses",
  },
  {
    id: "cleo-p4-7",
    period: 4,
    fichierPage: 120,
    guidePage: 271,
    title: "J'écris les mots avec h, ch, ph",
  },
  {
    id: "cleo-p4-8",
    period: 4,
    fichierPage: 124,
    guidePage: 273,
    title: "Je maitrise l'accent grave (è)",
  },
  {
    id: "cleo-p4-9",
    period: 4,
    fichierPage: 126,
    guidePage: 276,
    title: "J'écris les mots avec am, em, im, om",
  },
  {
    id: "cleo-p4-10",
    period: 4,
    fichierPage: 128,
    guidePage: 279,
    title: "Je manipule les groupes nominaux et les pronoms",
  },
  {
    id: "cleo-p4-11",
    period: 4,
    fichierPage: 130,
    guidePage: 281,
    title: "Je découvre les adverbes en -ment",
  },
  {
    id: "cleo-p4-12",
    period: 4,
    fichierPage: 134,
    guidePage: 284,
    title: "Je conjugue les verbes à l'imparfait",
  },
  {
    id: "cleo-p4-13",
    period: 4,
    fichierPage: 138,
    guidePage: 288,
    title: "Je coupe des phrases en groupes de sens",
  },

  // ── Période 5 ──────────────────────────────────────────────────────────
  {
    id: "cleo-p5-1",
    period: 5,
    fichierPage: 140,
    guidePage: 291,
    title: "J'écris les mots avec ail, eil, euil, ouil",
  },
  {
    id: "cleo-p5-2",
    period: 5,
    fichierPage: 142,
    guidePage: 293,
    title: "Je découvre les familles de mots (2)",
  },
  {
    id: "cleo-p5-3",
    period: 5,
    fichierPage: 144,
    guidePage: 296,
    title: "Je reconnais les noms propres et les noms communs",
  },
  {
    id: "cleo-p5-4",
    period: 5,
    fichierPage: 146,
    guidePage: 298,
    title: "Je découvre le passé composé",
  },
  {
    id: "cleo-p5-5",
    period: 5,
    fichierPage: 148,
    guidePage: 301,
    title: "Je transforme des phrases",
  },
  {
    id: "cleo-p5-6",
    period: 5,
    fichierPage: 150,
    guidePage: 304,
    title: "J'écris les mots avec ille, aille, eille, euille, ouille",
  },
  {
    id: "cleo-p5-7",
    period: 5,
    fichierPage: 152,
    guidePage: 307,
    title: "Je fais un dessin pour montrer que j'ai compris",
  },
  {
    id: "cleo-p5-8",
    period: 5,
    fichierPage: 154,
    guidePage: 309,
    title: "Je reconnais les familles de mots et les classes grammaticales",
  },
  {
    id: "cleo-p5-9",
    period: 5,
    fichierPage: 156,
    guidePage: 312,
    title: "Je manipule des adjectifs",
  },
  {
    id: "cleo-p5-10",
    period: 5,
    fichierPage: 158,
    guidePage: 314,
    title: "Je trouve le sujet et le verbe de la phrase (2)",
  },
  {
    id: "cleo-p5-11",
    period: 5,
    fichierPage: 160,
    guidePage: 317,
    title: "J'écris les mots avec gn ou gu",
  },
  {
    id: "cleo-p5-12",
    period: 5,
    fichierPage: 162,
    guidePage: 319,
    title: "Je découvre les préfixes",
  },
  {
    id: "cleo-p5-13",
    period: 5,
    fichierPage: 164,
    guidePage: 321,
    title: "Je découvre les niveaux de langue",
  },
  {
    id: "cleo-p5-14",
    period: 5,
    fichierPage: 166,
    guidePage: 324,
    title: "J'écris le masculin et le féminin des adjectifs",
  },
  {
    id: "cleo-p5-15",
    period: 5,
    fichierPage: 168,
    guidePage: 326,
    title: "J'organise les mots du général au particulier",
  },
  {
    id: "cleo-p5-16",
    period: 5,
    fichierPage: 172,
    guidePage: 329,
    title: "J'écris les mots avec oi, oin, ion",
  },
];
