/** Source exacte reprise de suivi_CE1D.html : exercices et pages Cléo. */
export type Ce1dExercise = {
  id: string;
  domain: "C" | "G" | "V" | "O";
  title: string;
  instruction: string;
};
export const CE1D_EXERCISES: Ce1dExercise[] = [
  {
    id: "e_p1_4",
    domain: "C",
    title: "Je comprends ce qui est caché dans un texte",
    instruction: "Lis attentivement le texte pour bien comprendre, puis réponds aux questions.",
  },
  {
    id: "e_p1_10",
    domain: "C",
    title: "J'associe des phrases et des images",
    instruction: "Observe bien chaque dessin. Puis barre les phrases qui ne vont pas avec eux.",
  },
  {
    id: "e_p1_11",
    domain: "V",
    title: "Je classe les noms en catégories",
    instruction:
      "Barre l'intrus qui se trouve parmi ces mots. Récris les mots dans les bonnes catégories.",
  },
  {
    id: "e_p1_12",
    domain: "G",
    title: "Je découvre le passé, le présent et le futur",
    instruction: "Entoure les verbes qui conviennent selon le temps de la phrase.",
  },
  {
    id: "e_p2_1",
    domain: "G",
    title: "Je choisis les bons déterminants",
    instruction:
      "Pour chaque dessin, écris une phrase avec ces mots. N'oublie pas d'ajouter des déterminants : le, la, l', les, un, une, des.",
  },
  {
    id: "e_p2_3",
    domain: "V",
    title: "Je fais attention à tous les détails de la phrase",
    instruction:
      "Écris les réponses aux devinettes en t'aidant des dessins. Attention, il y a des intrus.",
  },
  {
    id: "e_p2_4",
    domain: "C",
    title: "Je comprends des mots qui ont plusieurs sens",
    instruction:
      "Lis les phrases et observe bien les dessins. Entoure le mot et les dessins avec la couleur de la bonne définition.",
  },
  {
    id: "e_p2_5",
    domain: "G",
    title: "J'accorde le verbe avec le sujet (2)",
    instruction:
      "Pour chaque dessin, écris deux phrases différentes en changeant l'ordre des mots.",
  },
  {
    id: "e_p2_7",
    domain: "C",
    title: "Je comprends où commence et où finit une phrase",
    instruction:
      "Récris les phrases en ajoutant les majuscules et les signes de ponctuation (. ? !).",
  },
  {
    id: "e_p2_8",
    domain: "V",
    title: "Je découvre les diminutifs",
    instruction:
      "Complète les phrases avec c'est ou ce n'est pas et les mots manquants (petit animal).",
  },
  {
    id: "e_p2_9",
    domain: "G",
    title: "Je reconnais le verbe et le nom (1)",
    instruction:
      "Écris ces mots dans la bonne colonne : Verbes ou Noms. Écris le, la, l' ou les devant les noms.",
  },
  {
    id: "e_p2_11",
    domain: "C",
    title: "J'adapte ma lecture au fil du texte",
    instruction:
      "Lis attentivement le texte pour bien comprendre. Barre les dessins qui ne vont pas avec le texte.",
  },
  {
    id: "e_p2_12",
    domain: "O",
    title: "J'écris les mots avec rt, rp, rs, st, str...",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p2_13",
    domain: "G",
    title: "Je conjugue les verbes au présent avec il, elle ou ils, elles",
    instruction: "Complète les phrases avec le verbe et la terminaison qui conviennent.",
  },
  {
    id: "e_p2_14",
    domain: "V",
    title: "Je maîtrise l'apostrophe et les liaisons",
    instruction:
      "Récris les mots avec un n s'il en faut un, ou marque la liaison. Ajoute une apostrophe si nécessaire.",
  },
  {
    id: "e_p3_1",
    domain: "G",
    title: "Je trouve le sujet et le verbe de la phrase (1)",
    instruction:
      "Lis attentivement ces deux phrases. Barre celle qui ne veut rien dire. Souligne le sujet et le verbe de la phrase correcte.",
  },
  {
    id: "e_p3_2",
    domain: "V",
    title: "Je forme des mots nouveaux",
    instruction:
      "Forme tous les nouveaux mots possibles avec ces préfixes (dé-, re-, in-) et ces verbes ou adjectifs.",
  },
  {
    id: "e_p3_3",
    domain: "V",
    title: "Je découpe les mots en syllabes",
    instruction: "Découpe ces mots en syllabes, comme dans les exemples.",
  },
  {
    id: "e_p3_4",
    domain: "G",
    title: "Je conjugue les verbes au présent avec nous et vous",
    instruction: "Relie les étiquettes qui vont ensemble. Complète les phrases.",
  },
  {
    id: "e_p3_5",
    domain: "C",
    title: "Je lis différents types de documents",
    instruction: "Lis attentivement le texte pour bien comprendre. Réponds aux questions.",
  },
  {
    id: "e_p3_6",
    domain: "O",
    title: "J'écris les mots avec c ou qu",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p3_7",
    domain: "O",
    title: "Je maîtrise l'accent aigu (é)",
    instruction:
      "Découpe les mots en syllabes, comme dans l'exemple. Identifie où se place l'accent aigu.",
  },
  {
    id: "e_p3_8",
    domain: "G",
    title: "J'accorde l'adjectif avec le nom",
    instruction: "Complète chaque phrase avec un adjectif qui s'accorde avec le nom.",
  },
  {
    id: "e_p3_9",
    domain: "V",
    title: "Je trouve le sens d'adjectifs inconnus",
    instruction: "Lis les phrases. Entoure la définition qui correspond à l'adjectif souligné.",
  },
  {
    id: "e_p3_10",
    domain: "O",
    title: "J'écris les mots avec c ou ç",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p3_11",
    domain: "G",
    title: "Je conjugue les verbes être et avoir au présent",
    instruction: "Complète les phrases en conjuguant les verbes être ou avoir au présent.",
  },
  {
    id: "e_p3_12",
    domain: "G",
    title: "Je conjugue les verbes au présent avec je et tu",
    instruction: "Relie les étiquettes deux par deux pour faire un petit dialogue.",
  },
  {
    id: "e_p3_13",
    domain: "C",
    title: "Je comprends de qui ou de quoi on parle",
    instruction:
      "Lis attentivement le texte. Indique à qui ou à quoi correspondent les mots en gras.",
  },
  {
    id: "e_p3_14",
    domain: "G",
    title: "J'écris des verbes au pluriel",
    instruction: "Lis toutes ces phrases. Mets les verbes au pluriel en changeant le sujet.",
  },
  {
    id: "e_p3_15",
    domain: "C",
    title: "Je comprends le sens propre et le sens figuré",
    instruction:
      "Lis les expressions et observe les dessins. Écris si le verbe est utilisé au sens propre ou au sens figuré.",
  },
  {
    id: "e_p4_1",
    domain: "G",
    title: "Je connais les pronoms sujets",
    instruction:
      "Relie les étiquettes qui vont ensemble. Remplace le groupe nominal sujet par un pronom.",
  },
  {
    id: "e_p4_2",
    domain: "G",
    title: "Je conjugue les verbes au futur",
    instruction: "Invente des phrases avec les étiquettes proposées. Conjugue les verbes au futur.",
  },
  {
    id: "e_p4_3",
    domain: "O",
    title: "J'écris les mots avec g ou ge",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p4_4",
    domain: "O",
    title: "J'écris les mots avec in/ine, ain/aine, ein/eine, un/une",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p4_5",
    domain: "G",
    title: "Je reconnais le verbe et le nom (2)",
    instruction: "Dans chaque encadré, barre le ou les intrus.",
  },
  {
    id: "e_p4_6",
    domain: "C",
    title: "Je comprends dans quel ordre se passent les choses",
    instruction: "Observe le dessin et lis les phrases. Numérote-les dans l'ordre chronologique.",
  },
  {
    id: "e_p4_7",
    domain: "O",
    title: "J'écris les mots avec h, ch, ph",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p4_8",
    domain: "O",
    title: "Je maîtrise l'accent grave (è)",
    instruction: "Complète les mots avec è ou e.",
  },
  {
    id: "e_p4_9",
    domain: "O",
    title: "J'écris les mots avec am, em, im, om",
    instruction: "Complète les mots.",
  },
  {
    id: "e_p4_10",
    domain: "G",
    title: "Je manipule les groupes nominaux et les pronoms",
    instruction:
      "Relie les étiquettes qui vont ensemble. Remplace le groupe nominal par un pronom.",
  },
  {
    id: "e_p4_11",
    domain: "V",
    title: "Je découvre les adverbes en -ment",
    instruction:
      "Relie deux par deux les mots qui ont un sens contraire. Forme des adverbes en -ment.",
  },
  {
    id: "e_p4_12",
    domain: "G",
    title: "Je conjugue les verbes à l'imparfait",
    instruction:
      "Invente des phrases avec les étiquettes proposées. Conjugue les verbes à l'imparfait.",
  },
  {
    id: "e_p4_13",
    domain: "C",
    title: "Je coupe des phrases en groupes de sens",
    instruction: "Lis attentivement cette phrase. Souligne les groupes de sens.",
  },
  {
    id: "e_p4_14",
    domain: "O",
    title: "J'écris les mots avec ail, eil, euil, ouil",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p4_15",
    domain: "V",
    title: "Je découvre les familles de mots (2)",
    instruction: "Relie deux à deux les mots de la même famille.",
  },
  {
    id: "e_p5_1",
    domain: "G",
    title: "Je reconnais les noms propres et les noms communs",
    instruction: "Relie les étiquettes deux par deux. Entoure les noms propres.",
  },
  {
    id: "e_p5_2",
    domain: "G",
    title: "Je découvre le passé composé",
    instruction: "Relie les phrases qui se ressemblent. Forme des phrases au passé composé.",
  },
  {
    id: "e_p5_3",
    domain: "G",
    title: "Je transforme des phrases",
    instruction: "Écris deux phrases sous les dessins avec ces étiquettes.",
  },
  {
    id: "e_p5_4",
    domain: "O",
    title: "J'écris les mots avec ille, aille, eille, euille, ouille",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p5_5",
    domain: "C",
    title: "Je fais un dessin pour montrer que j'ai compris",
    instruction: "Lis attentivement le texte. Fais un dessin pour illustrer ce que tu as compris.",
  },
  {
    id: "e_p5_6",
    domain: "V",
    title: "Je reconnais les familles de mots et les classes grammaticales",
    instruction:
      "Lis le dialogue. Relie les mots de la même famille et indique leur classe grammaticale.",
  },
  {
    id: "e_p5_7",
    domain: "G",
    title: "Je manipule des adjectifs",
    instruction: "Colorie en bleu les groupes nominaux si les mots sont dans le bon ordre.",
  },
  {
    id: "e_p5_8",
    domain: "G",
    title: "Je trouve le sujet et le verbe de la phrase (2)",
    instruction:
      "Lis les deux phrases et barre celle qui ne veut rien dire. Souligne le sujet et le verbe.",
  },
  {
    id: "e_p5_9",
    domain: "O",
    title: "J'écris les mots avec gn ou gu",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p5_10",
    domain: "V",
    title: "Je découvre les préfixes",
    instruction: "Lis les définitions. Trouve les mots formés avec les préfixes.",
  },
  {
    id: "e_p5_11",
    domain: "V",
    title: "Je découvre les niveaux de langue",
    instruction: "Relie les mots qui ont le même sens. Indique le niveau de langue.",
  },
  {
    id: "e_p5_12",
    domain: "O",
    title: "J'écris le masculin et le féminin des adjectifs",
    instruction: "Observe comment on passe du féminin au masculin. Complète le tableau.",
  },
  {
    id: "e_p5_13",
    domain: "V",
    title: "J'organise les mots du général au particulier",
    instruction: "Trouve les mots qui font partie de la même catégorie.",
  },
  {
    id: "e_p5_14",
    domain: "O",
    title: "J'écris les mots avec oi, oin, ion",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
];
export const CE1D_PAGE_MAP: Record<number, string[]> = {
  "60": ["e_p2_14"],
  "61": ["e_p1_12", "e_p1_10", "e_p2_8"],
  "62": ["e_p2_4", "e_p1_11"],
  "63": ["e_p2_7", "e_p1_4", "e_p2_14"],
  "64": ["e_p2_13", "e_p2_1"],
  "65": ["e_p1_10", "e_p2_4"],
  "66": ["e_p2_7", "e_p2_9"],
  "67": ["e_p2_14", "e_p2_11", "e_p2_4"],
  "68": ["e_p3_1"],
  "69": ["e_p2_14", "e_p2_8", "e_p2_3"],
  "70": ["e_p3_2"],
  "71": ["e_p2_14", "e_p1_4", "e_p2_13"],
  "72": ["e_p2_5", "e_p2_9"],
  "73": ["e_p2_7", "e_p2_3", "e_p3_2"],
  "74": ["e_p3_3"],
  "75": ["e_p1_10", "e_p2_11", "e_p2_5"],
  "76": ["e_p3_4"],
  "77": ["e_p3_2", "e_p3_3", "e_p1_4"],
  "78": ["e_p3_5"],
  "79": ["e_p3_1", "e_p2_3", "e_p3_3"],
  "80": ["e_p2_7", "e_p3_4"],
  "81": ["e_p2_11", "e_p3_2", "e_p3_5"],
  "82": ["e_p3_6"],
  "83": ["e_p3_1", "e_p3_5", "e_p2_7"],
  "84": ["e_p3_7"],
  "85": ["e_p3_6", "e_p3_4"],
  "86": ["e_p3_8"],
  "87": ["e_p3_7", "e_p3_5", "e_p3_6"],
  "88": ["e_p3_9"],
  "89": ["e_p3_7", "e_p1_4", "e_p2_9"],
  "90": ["e_p3_10"],
  "91": ["e_p3_9", "e_p3_5", "e_p3_1"],
  "92": ["e_p3_11"],
  "93": ["e_p2_7", "e_p1_4", "e_p3_7"],
  "94": ["e_p3_12"],
  "95": ["e_p3_9", "e_p1_4", "e_p3_8"],
  "96": ["e_p3_1", "e_p3_12", "e_p3_11"],
  "97": ["e_p3_5", "e_p3_7"],
  "98": ["e_p3_13"],
  "99": ["e_p3_1", "e_p3_9", "e_p3_10"],
  "100": ["e_p3_14"],
  "101": ["e_p3_12", "e_p1_4", "e_p3_8"],
  "102": ["e_p3_15"],
  "103": ["e_p3_14", "e_p3_8", "e_p3_13"],
  "104": ["e_p4_1"],
  "105": ["e_p3_8", "e_p3_10", "e_p3_13"],
  "106": ["e_p3_12", "e_p3_13", "e_p3_11"],
  "107": ["e_p3_14", "e_p3_15"],
  "108": ["e_p4_2"],
  "109": ["e_p4_1", "e_p3_13", "e_p3_8"],
  "110": ["e_p4_3"],
  "111": ["e_p1_4", "e_p4_2", "e_p3_9"],
  "112": ["e_p3_8", "e_p4_1"],
  "113": ["e_p3_13", "e_p3_15", "e_p4_3"],
  "114": ["e_p4_4"],
  "115": ["e_p3_9", "e_p1_4", "e_p4_2"],
  "116": ["e_p4_5"],
  "117": ["e_p3_15", "e_p3_14", "e_p1_4"],
  "118": ["e_p4_6"],
  "119": ["e_p3_9", "e_p4_3", "e_p4_2"],
  "120": ["e_p4_7"],
  "121": ["e_p3_15", "e_p4_6", "e_p4_5"],
  "122": ["e_p3_14", "e_p4_4"],
  "123": ["e_p1_4", "e_p4_2", "e_p4_7"],
  "124": ["e_p4_8"],
  "125": ["e_p4_5", "e_p4_6", "e_p3_8"],
  "126": ["e_p4_9"],
  "127": ["e_p3_15", "e_p1_4", "e_p4_2"],
  "128": ["e_p4_10"],
  "129": ["e_p4_8", "e_p4_6"],
  "130": ["e_p4_11"],
  "131": ["e_p3_8", "e_p4_9", "e_p1_4"],
  "132": ["e_p4_5", "e_p4_10"],
  "133": ["e_p4_8", "e_p4_6", "e_p3_15"],
  "134": ["e_p4_12"],
  "135": ["e_p4_11", "e_p1_4", "e_p4_4"],
  "136": ["e_p4_10", "e_p4_5"],
  "137": ["e_p3_15", "e_p4_6", "e_p4_8"],
  "138": ["e_p4_13"],
  "139": ["e_p1_4", "e_p4_9", "e_p4_11"],
  "140": ["e_p4_14"],
  "141": ["e_p3_15", "e_p4_6", "e_p4_13"],
  "142": ["e_p4_15"],
  "143": ["e_p1_4", "e_p4_12"],
  "144": ["e_p5_1"],
  "145": ["e_p4_5", "e_p4_15", "e_p4_6"],
  "146": ["e_p5_2"],
  "147": ["e_p1_4", "e_p4_12"],
  "148": ["e_p5_3"],
  "149": ["e_p4_13", "e_p5_1", "e_p5_2"],
  "150": ["e_p5_4"],
  "151": ["e_p4_12", "e_p4_15", "e_p4_6"],
  "152": ["e_p5_5"],
  "153": ["e_p5_4", "e_p5_1", "e_p5_2"],
  "154": ["e_p5_6"],
  "155": ["e_p4_12", "e_p4_15", "e_p5_5"],
  "156": ["e_p5_7"],
  "157": ["e_p5_3", "e_p5_1", "e_p1_4"],
  "158": ["e_p5_8"],
  "159": ["e_p4_15", "e_p5_2"],
  "160": ["e_p5_9"],
  "161": ["e_p5_6", "e_p4_6", "e_p5_8"],
  "162": ["e_p5_10"],
  "163": ["e_p5_7", "e_p5_9"],
  "164": ["e_p5_11"],
  "165": ["e_p5_8", "e_p5_3", "e_p5_5"],
  "166": ["e_p5_12"],
  "167": ["e_p4_6", "e_p5_9", "e_p5_6"],
  "168": ["e_p5_13"],
  "169": ["e_p4_15", "e_p1_4", "e_p5_7"],
  "170": ["e_p5_8", "e_p4_6", "e_p5_13"],
  "171": ["e_p5_3", "e_p5_2", "e_p5_11"],
  "172": ["e_p5_14"],
  "173": ["e_p5_10", "e_p5_12", "e_p5_11"],
  "174": ["e_p5_8", "e_p5_12", "e_p5_13"],
  "175": ["e_p5_10", "e_p5_14"],
};

/** Pages exactes du cahier de corrigés Cléo CE1 utilisé pour la correction. */
export const CE1D_CORRIGES_PAGE_MAP: Record<string, number> = {
  e_p1_4: 8,
  e_p1_10: 24,
  e_p1_11: 26,
  e_p1_12: 28,
  e_p2_1: 32,
  e_p2_3: 36,
  e_p2_4: 38,
  e_p2_5: 40,
  e_p2_7: 44,
  e_p2_8: 46,
  e_p2_9: 48,
  e_p2_11: 52,
  e_p2_12: 56,
  e_p2_13: 58,
  e_p2_14: 60,
  e_p3_1: 68,
  e_p3_2: 70,
  e_p3_3: 74,
  e_p3_4: 76,
  e_p3_5: 78,
  e_p3_6: 82,
  e_p3_7: 84,
  e_p3_8: 86,
  e_p3_9: 88,
  e_p3_10: 90,
  e_p3_11: 92,
  e_p3_12: 94,
  e_p3_13: 98,
  e_p3_14: 100,
  e_p3_15: 102,
  e_p4_1: 104,
  e_p4_2: 108,
  e_p4_3: 110,
  e_p4_4: 114,
  e_p4_5: 116,
  e_p4_6: 118,
  e_p4_7: 120,
  e_p4_8: 124,
  e_p4_9: 126,
  e_p4_10: 128,
  e_p4_11: 130,
  e_p4_12: 134,
  e_p4_13: 138,
  e_p4_14: 140,
  e_p4_15: 142,
  e_p5_1: 144,
  e_p5_2: 146,
  e_p5_3: 148,
  e_p5_4: 150,
  e_p5_5: 152,
  e_p5_6: 154,
  e_p5_7: 156,
  e_p5_8: 158,
  e_p5_9: 160,
  e_p5_10: 162,
  e_p5_11: 164,
  e_p5_12: 166,
  e_p5_13: 168,
  e_p5_14: 172,
};
