/**
 * Base complète du cahier de corrigés Cléo CE1, reconstruite à partir du
 * sommaire officiel et du PDF FichierCE1_Corriges.pdf (édition 2025).
 */

export type CleoWorkbookExercise = {
  id: string;
  domain: "C" | "V" | "G" | "O";
  period: 1 | 2 | 3 | 4 | 5;
  fichierPage: number;
  guidePage: number;
  title: string;
  instruction: string;
};

export const CLEO_WORKBOOK_EXERCISES: CleoWorkbookExercise[] = [
  {
    id: "e_p1_1",
    domain: "C",
    period: 1,
    fichierPage: 8,
    guidePage: 120,
    title: "Je comprends ce qui est « caché » dans un texte",
    instruction: "Lis attentivement le texte pour bien comprendre. Réponds aux questions.",
  },
  {
    id: "e_p1_2",
    domain: "V",
    period: 1,
    fichierPage: 9,
    guidePage: 125,
    title: "Je classe les mots dans l'ordre alphabétique",
    instruction:
      "Écris les noms des animaux dans l’ordre alphabétique. Colorie l’initiale de chaque mot.",
  },
  {
    id: "e_p1_3",
    domain: "G",
    period: 1,
    fichierPage: 10,
    guidePage: 128,
    title: "Je découvre le singulier et le pluriel des noms",
    instruction:
      "Écris chaque nom avec un déterminant au bon endroit. Vérifie et complète son travail.",
  },
  {
    id: "e_p1_4",
    domain: "O",
    period: 1,
    fichierPage: 12,
    guidePage: 133,
    title: "J'écris les mots avec oi, ou, on",
    instruction:
      "Écris les mots qui correspondent aux dessins avec ces syllabes. Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p1_5",
    domain: "C",
    period: 1,
    fichierPage: 14,
    guidePage: 136,
    title: "Je comprends des phrases complexes",
    instruction: "Lis attentivement ces phrases. Colorie le dessin comme indiqué.",
  },
  {
    id: "e_p1_6",
    domain: "V",
    period: 1,
    fichierPage: 16,
    guidePage: 139,
    title: "Je découvre les familles de mots (1)",
    instruction:
      "Entoure tous les mots de la famille de chat. Entoure tous les mots de la famille de jardin.",
  },
  {
    id: "e_p1_7",
    domain: "O",
    period: 1,
    fichierPage: 18,
    guidePage: 142,
    title: "J'écris les mots avec i/in, ai/ain",
    instruction:
      "Écris les mots qui correspondent aux dessins avec ces syllabes. Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p1_8",
    domain: "G",
    period: 1,
    fichierPage: 20,
    guidePage: 144,
    title: "J'accorde le verbe avec le sujet (1)",
    instruction: "Pour chaque dessin, écris une phrase avec ces mots.",
  },
  {
    id: "e_p1_9",
    domain: "O",
    period: 1,
    fichierPage: 22,
    guidePage: 147,
    title: "J'écris les mots avec ar/ra, ir/ri, or/ro…",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p1_10",
    domain: "C",
    period: 1,
    fichierPage: 24,
    guidePage: 149,
    title: "J'associe des phrases et des images",
    instruction: "Observe bien le dessin. Puis barre les phrases qui ne vont pas avec lui.",
  },
  {
    id: "e_p1_11",
    domain: "V",
    period: 1,
    fichierPage: 26,
    guidePage: 153,
    title: "Je classe les noms en catégories",
    instruction:
      "Barre l'intrus qui se trouve parmi ces mots. Récris les mots dans les cadres ci-dessous.",
  },
  {
    id: "e_p1_12",
    domain: "G",
    period: 1,
    fichierPage: 28,
    guidePage: 157,
    title: "Je découvre le passé, le présent et le futur",
    instruction:
      "Complète les phrases à l'aide de ces étiquettes. Dans ces phrases, entoure les verbes.",
  },
  {
    id: "e_p1_13",
    domain: "O",
    period: 1,
    fichierPage: 30,
    guidePage: 162,
    title: "J'écris les mots avec ai, an, au, eau",
    instruction:
      "Écris les mots qui correspondent aux dessins avec ces syllabes. Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p2_1",
    domain: "G",
    period: 2,
    fichierPage: 32,
    guidePage: 164,
    title: "Je choisis les bons déterminants",
    instruction: "Pour chaque dessin, écris une phrase avec ces mots.",
  },
  {
    id: "e_p2_2",
    domain: "O",
    period: 2,
    fichierPage: 34,
    guidePage: 167,
    title: "J'écris les mots avec g ou gu",
    instruction:
      "Écris les mots qui correspondent aux dessins. Écris les mots qui correspondent aux dessins avec ces syllabes.",
  },
  {
    id: "e_p2_3",
    domain: "V",
    period: 2,
    fichierPage: 36,
    guidePage: 170,
    title: "Je fais attention à tous les détails de la phrase",
    instruction: "Pour chaque phrase, entoure le bon dessin. Fais attention à tous les détails.",
  },
  {
    id: "e_p2_4",
    domain: "C",
    period: 2,
    fichierPage: 38,
    guidePage: 174,
    title: "Je comprends des mots qui ont plusieurs sens",
    instruction:
      "Lis les phrases et observe bien les dessins. Ci-dessus, entoure le nom buche et les dessins avec la couleur de la bonne définition.",
  },
  {
    id: "e_p2_5",
    domain: "G",
    period: 2,
    fichierPage: 40,
    guidePage: 176,
    title: "J'accorde le verbe avec le sujet (2)",
    instruction: "Pour chaque dessin, écris deux phrases différentes avec ces mots.",
  },
  {
    id: "e_p2_6",
    domain: "O",
    period: 2,
    fichierPage: 42,
    guidePage: 179,
    title: "J'écris les mots avec elle, ette, esse, enne, erre",
    instruction:
      "Écris les mots qui correspondent aux dessins avec ces débuts et ces fins de mots. Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p2_7",
    domain: "C",
    period: 2,
    fichierPage: 44,
    guidePage: 182,
    title: "Je comprends où commence et où finit une phrase",
    instruction:
      "Récris les phrases en ajoutant les majuscules et les signes de ponctuation. Souligne en bleu les phrases déclaratives , en vert les phrases interrogatives , en noir les phrases impératives.",
  },
  {
    id: "e_p2_8",
    domain: "V",
    period: 2,
    fichierPage: 46,
    guidePage: 187,
    title: "Je découvre les diminutifs",
    instruction:
      "Comme dans l'exemple, complète les phrases avec c’est ou ce n’est pas et les mots manquants. Relie les mots qui se ressemblent.",
  },
  {
    id: "e_p2_9",
    domain: "G",
    period: 2,
    fichierPage: 48,
    guidePage: 190,
    title: "Je reconnais le verbe et le nom (1)",
    instruction: "Écris ces mots dans la bonne colonne. Écris le, la, l’ ou les devant les noms.",
  },
  {
    id: "e_p2_10",
    domain: "O",
    period: 2,
    fichierPage: 50,
    guidePage: 194,
    title: "J'écris les mots avec s ou ss",
    instruction: "Écris les mots qui correspondent aux dessins. Écris ces mots avec s ou ss.",
  },
  {
    id: "e_p2_11",
    domain: "C",
    period: 2,
    fichierPage: 52,
    guidePage: 197,
    title: "J'adapte ma lecture au fil du texte",
    instruction:
      "Lis attentivement le texte pour bien comprendre. Au fur et à mesure de ta lecture, barre les dessins qui ne vont pas avec le texte.",
  },
  {
    id: "e_p2_12",
    domain: "O",
    period: 2,
    fichierPage: 56,
    guidePage: 200,
    title: "J'écris les mots avec rt, rp, rs, st, str…",
    instruction: "Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p2_13",
    domain: "G",
    period: 2,
    fichierPage: 58,
    guidePage: 202,
    title: "Je conjugue les verbes au présent avec il, elle ou ils, elles",
    instruction:
      "Complète les phrases avec le verbe et la terminaison qui conviennent. Souligne les lettres qui montrent que l'on est au pluriel.",
  },
  {
    id: "e_p2_14",
    domain: "V",
    period: 2,
    fichierPage: 60,
    guidePage: 207,
    title: "Je maitrise l'apostrophe et les liaisons",
    instruction:
      "Récris les mots avec un n s’il en faut un, ou marque la liaison comme dans l’exemple.",
  },
  {
    id: "e_p3_1",
    domain: "G",
    period: 3,
    fichierPage: 68,
    guidePage: 210,
    title: "Je trouve le sujet et le verbe de la phrase (1)",
    instruction: "Lis attentivement ces deux phrases. Puis barre celle qui ne veut rien dire.",
  },
  {
    id: "e_p3_2",
    domain: "V",
    period: 3,
    fichierPage: 70,
    guidePage: 213,
    title: "Je forme des mots nouveaux",
    instruction:
      "Observe ces exemples. Complète ces phrases en formant des mots avec dé- , re- ou in- et les mots roses.",
  },
  {
    id: "e_p3_3",
    domain: "V",
    period: 3,
    fichierPage: 74,
    guidePage: 216,
    title: "Je découpe les mots en syllabes",
    instruction:
      "Découpe ces mots en syllabes, comme dans les exemples. Continue à découper les mots en syllabes.",
  },
  {
    id: "e_p3_4",
    domain: "G",
    period: 3,
    fichierPage: 76,
    guidePage: 221,
    title: "Je conjugue les verbes au présent avec nous et vous",
    instruction: "Relie les étiquettes qui vont ensemble. Souligne la terminaison des verbes.",
  },
  {
    id: "e_p3_5",
    domain: "C",
    period: 3,
    fichierPage: 78,
    guidePage: 224,
    title: "Je lis différents types de documents",
    instruction:
      "Lis attentivement le texte pour bien comprendre. Entoure le tableau que la maitresse a donné à Lily.",
  },
  {
    id: "e_p3_6",
    domain: "O",
    period: 3,
    fichierPage: 82,
    guidePage: 226,
    title: "J'écris les mots avec c ou qu",
    instruction:
      "Écris les mots qui correspondent aux dessins avec ces syllabes. Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p3_7",
    domain: "O",
    period: 3,
    fichierPage: 84,
    guidePage: 228,
    title: "Je maitrise l'accent aigu (é)",
    instruction:
      "À gauche, ajoute l’accent aigu (é) quand il le faut. Puis recopie les mots à droite en cachant le modèle.",
  },
  {
    id: "e_p3_8",
    domain: "G",
    period: 3,
    fichierPage: 86,
    guidePage: 232,
    title: "J'accorde l'adjectif avec le nom",
    instruction:
      "Complète chaque phrase avec un adjectif de couleur au choix. Relis ton texte et colorie le dessin.",
  },
  {
    id: "e_p3_9",
    domain: "V",
    period: 3,
    fichierPage: 88,
    guidePage: 236,
    title: "Je trouve le sens d'adjectifs inconnus",
    instruction:
      "Lis le texte puis les phrases. Entoure les mots qui ont le même sens que l’adjectif souligné.",
  },
  {
    id: "e_p3_10",
    domain: "O",
    period: 3,
    fichierPage: 90,
    guidePage: 238,
    title: "J'écris les mots avec c ou ç",
    instruction:
      "Écris les mots qui correspondent aux dessins avec ces syllabes. Écris les mots qui correspondent aux dessins.",
  },
  {
    id: "e_p3_11",
    domain: "G",
    period: 3,
    fichierPage: 92,
    guidePage: 240,
    title: "Je conjugue les verbes être et avoir au présent",
    instruction:
      "Lis les deux phrases à droite. Puis récris-les en remplaçant Mon chat par Mes chats.",
  },
  {
    id: "e_p3_12",
    domain: "G",
    period: 3,
    fichierPage: 94,
    guidePage: 243,
    title: "Je conjugue les verbes au présent avec je et tu",
    instruction: "Complète les phrases avec le verbe et la terminaison qui conviennent.",
  },
  {
    id: "e_p3_13",
    domain: "C",
    period: 3,
    fichierPage: 98,
    guidePage: 245,
    title: "Je comprends de qui ou de quoi on parle",
    instruction:
      "Lis attentivement le texte. Colorie les mots entourés : – en jaune s’ils désignent Hélène – en vert s’ils désignent les fleurs",
  },
  {
    id: "e_p3_14",
    domain: "G",
    period: 3,
    fichierPage: 100,
    guidePage: 248,
    title: "J'écris des verbes au pluriel",
    instruction: "Lis le texte. Transforme les phrases en écrivant les verbes au pluriel.",
  },
  {
    id: "e_p3_15",
    domain: "C",
    period: 3,
    fichierPage: 102,
    guidePage: 250,
    title: "Je comprends le sens propre et le sens figuré",
    instruction:
      "Entoure le même verbe dans toutes les phrases. Écris à droite s’il est utilisé au sens propre ou au sens figuré.",
  },
  {
    id: "e_p4_1",
    domain: "G",
    period: 4,
    fichierPage: 104,
    guidePage: 253,
    title: "Je connais les pronoms sujets",
    instruction:
      "Complète le texte avec les pronoms sujets qui conviennent. Colorie de la même couleur les personnes dont on parle et les pronoms sujets qui les désignent.",
  },
  {
    id: "e_p4_2",
    domain: "G",
    period: 4,
    fichierPage: 108,
    guidePage: 256,
    title: "Je conjugue les verbes au futur",
    instruction:
      "Dans ce texte, souligne les verbes au futur. Puis relie leur sujet avec une flèche.",
  },
  {
    id: "e_p4_3",
    domain: "O",
    period: 4,
    fichierPage: 110,
    guidePage: 259,
    title: "J'écris les mots avec g ou ge",
    instruction:
      "Écris les mots qui correspondent aux dessins. Colorie les syllabes qui contiennent un g.",
  },
  {
    id: "e_p4_4",
    domain: "O",
    period: 4,
    fichierPage: 114,
    guidePage: 262,
    title: "J'écris les mots avec in/ine, ain/aine, ein/eine, un/une",
    instruction:
      "Écris les mots qui correspondent aux dessins. Écris la fin des phrases en cachant la dernière lettre des mots féminins.",
  },
  {
    id: "e_p4_5",
    domain: "G",
    period: 4,
    fichierPage: 116,
    guidePage: 264,
    title: "Je reconnais le verbe et le nom (2)",
    instruction: "Barre le ou les intrus. Puis, dans l'encadré à droite, entoure la bonne réponse.",
  },
  {
    id: "e_p4_6",
    domain: "C",
    period: 4,
    fichierPage: 118,
    guidePage: 266,
    title: "Je comprends dans quel ordre se passent les choses",
    instruction:
      "Observe les dessins et lis les phrases. Dans chaque colonne, numérote les cases de 1 à 5.",
  },
  {
    id: "e_p4_7",
    domain: "O",
    period: 4,
    fichierPage: 120,
    guidePage: 271,
    title: "J'écris les mots avec h, ch, ph",
    instruction:
      "Écris les mots qui correspondent aux dessins. Écris les mots qui correspondent aux dessins avec ces syllabes.",
  },
  {
    id: "e_p4_8",
    domain: "O",
    period: 4,
    fichierPage: 124,
    guidePage: 273,
    title: "Je maitrise l'accent grave (è)",
    instruction: "Complète les mots avec è ou e. Puis découpe les mots en syllabes.",
  },
  {
    id: "e_p4_9",
    domain: "O",
    period: 4,
    fichierPage: 126,
    guidePage: 276,
    title: "J'écris les mots avec am, em, im, om",
    instruction:
      "Complète les mots. Écris les mots qui correspondent aux dessins avec ces syllabes.",
  },
  {
    id: "e_p4_10",
    domain: "G",
    period: 4,
    fichierPage: 128,
    guidePage: 279,
    title: "Je manipule les groupes nominaux et les pronoms",
    instruction:
      "Complète chaque phrase avec un groupe nominal avec un déterminant , un nom et un adjectif. Colorie de la même couleur ton groupe nominal et le pronom qui le remplace dans la deuxième phrase.",
  },
  {
    id: "e_p4_11",
    domain: "V",
    period: 4,
    fichierPage: 130,
    guidePage: 281,
    title: "Je découvre les adverbes en -ment",
    instruction:
      "Complète les phrases avec un adverbe en -ment. Relie deux par deux les mots qui ont un sens contraire.",
  },
  {
    id: "e_p4_12",
    domain: "G",
    period: 4,
    fichierPage: 134,
    guidePage: 284,
    title: "Je conjugue les verbes à l'imparfait",
    instruction: "Souligne les verbes à l’imparfait. Puis relie leur sujet avec une flèche.",
  },
  {
    id: "e_p4_13",
    domain: "C",
    period: 4,
    fichierPage: 138,
    guidePage: 288,
    title: "Je coupe des phrases en groupes de sens",
    instruction: "Lis attentivement cette phrase. Puis trace des traits entre les groupes de sens.",
  },
  {
    id: "e_p5_1",
    domain: "O",
    period: 5,
    fichierPage: 140,
    guidePage: 291,
    title: "J'écris les mots avec ail, eil, euil, ouil",
    instruction:
      "Écris les mots qui correspondent aux dessins. Écris les mots qui correspondent aux dessins en associant ces débuts et ces fins de mots.",
  },
  {
    id: "e_p5_2",
    domain: "V",
    period: 5,
    fichierPage: 142,
    guidePage: 293,
    title: "Je découvre les familles de mots (2)",
    instruction:
      "Colorie en jaune les mots de la première famille, en vert les mots de la seconde famille. Relie deux à deux les mots de la même famille.",
  },
  {
    id: "e_p5_3",
    domain: "G",
    period: 5,
    fichierPage: 144,
    guidePage: 296,
    title: "Je reconnais les noms propres et les noms communs",
    instruction: "Relie deux par deux les étiquettes. Écris les noms propres qui manquent.",
  },
  {
    id: "e_p5_4",
    domain: "G",
    period: 5,
    fichierPage: 146,
    guidePage: 298,
    title: "Je découvre le passé composé",
    instruction:
      "Écris quatre phrases au passé composé avec ces étiquettes. Relie les phrases qui se ressemblent.",
  },
  {
    id: "e_p5_5",
    domain: "G",
    period: 5,
    fichierPage: 148,
    guidePage: 301,
    title: "Je transforme des phrases",
    instruction:
      "Écris deux phrases sous les dessins avec ces étiquettes. Colorie de la même couleur les mots et les terminaisons qui changent d’une phrase à l’autre.",
  },
  {
    id: "e_p5_6",
    domain: "O",
    period: 5,
    fichierPage: 150,
    guidePage: 304,
    title: "J'écris les mots avec ille, aille, eille, euille, ouille",
    instruction:
      "Écris les mots qui correspondent aux dessins. Écris les mots qui correspondent aux dessins en associant ces débuts et ces fins de mots.",
  },
  {
    id: "e_p5_7",
    domain: "C",
    period: 5,
    fichierPage: 152,
    guidePage: 307,
    title: "Je fais un dessin pour montrer que j'ai compris",
    instruction: "Lis attentivement le texte. Complète le dessin en respectant le texte.",
  },
  {
    id: "e_p5_8",
    domain: "V",
    period: 5,
    fichierPage: 154,
    guidePage: 309,
    title: "Je reconnais les familles de mots et les classes grammaticales",
    instruction: "Lis le dialogue. Entoure les trois mots qui sont de la même famille.",
  },
  {
    id: "e_p5_9",
    domain: "G",
    period: 5,
    fichierPage: 156,
    guidePage: 312,
    title: "Je manipule des adjectifs",
    instruction:
      "Lis attentivement ces phrases. Colorie en bleu les groupes nominaux si les mots sont dans le bon ordre.",
  },
  {
    id: "e_p5_10",
    domain: "G",
    period: 5,
    fichierPage: 158,
    guidePage: 314,
    title: "Je trouve le sujet et le verbe de la phrase (2)",
    instruction:
      "Lis cette phrase qui ne veut rien dire. Récris-la en mettant les mots dans l’ordre.",
  },
  {
    id: "e_p5_11",
    domain: "O",
    period: 5,
    fichierPage: 160,
    guidePage: 317,
    title: "J'écris les mots avec gn ou gu",
    instruction:
      "Écris les mots qui correspondent aux dessins. Écris les mots qui correspondent aux dessins avec ces syllabes.",
  },
  {
    id: "e_p5_12",
    domain: "V",
    period: 5,
    fichierPage: 162,
    guidePage: 319,
    title: "Je découvre les préfixes",
    instruction:
      "Lis chaque définition. Écris les mots qui correspondent aux définitions avec ces préfixes et ces fins de mots.",
  },
  {
    id: "e_p5_13",
    domain: "V",
    period: 5,
    fichierPage: 164,
    guidePage: 321,
    title: "Je découvre les niveaux de langue",
    instruction:
      "Lis les petits textes. Dans chaque texte, entoure les deux mots qui ont le même sens.",
  },
  {
    id: "e_p5_14",
    domain: "O",
    period: 5,
    fichierPage: 166,
    guidePage: 324,
    title: "J'écris le masculin et le féminin des adjectifs",
    instruction: "Cache la fin de l’ adjectif au féminin. Puis écris l’ adjectif au masculin.",
  },
  {
    id: "e_p5_15",
    domain: "V",
    period: 5,
    fichierPage: 168,
    guidePage: 326,
    title: "J'organise les mots du général au particulier",
    instruction: "Observe bien ces mots. Trouve les mots qui font partie de la même catégorie.",
  },
  {
    id: "e_p5_16",
    domain: "O",
    period: 5,
    fichierPage: 172,
    guidePage: 329,
    title: "J'écris les mots avec oi, oin, ion",
    instruction:
      "Écris les mots qui correspondent aux dessins avec ces syllabes. Écris les mots qui correspondent aux dessins.",
  },
];

export const CLEO_WORKBOOK_PAGE_MAP: Record<number, string[]> = {
  8: ["e_p1_1"],
  9: ["e_p1_2"],
  10: ["e_p1_3"],
  11: ["e_p1_2", "e_p1_1", "e_p1_3"],
  12: ["e_p1_4"],
  13: ["e_p1_2", "e_p1_1", "e_p1_3"],
  14: ["e_p1_5"],
  15: ["e_p1_4", "e_p1_2", "e_p1_3"],
  16: ["e_p1_6"],
  17: ["e_p1_5", "e_p1_4", "e_p1_3"],
  18: ["e_p1_7"],
  19: ["e_p1_1", "e_p1_3", "e_p1_6"],
  20: ["e_p1_8"],
  21: ["e_p1_5", "e_p1_6", "e_p1_7"],
  22: ["e_p1_9"],
  23: ["e_p1_2", "e_p1_1", "e_p1_8"],
  24: ["e_p1_10"],
  25: ["e_p1_6", "e_p1_8", "e_p1_7"],
  26: ["e_p1_11"],
  27: ["e_p1_5", "e_p1_3", "e_p1_9"],
  28: ["e_p1_12"],
  29: ["e_p1_1", "e_p1_8", "e_p1_6"],
  30: ["e_p1_13"],
  31: ["e_p1_11", "e_p1_10", "e_p1_12"],
  32: ["e_p2_1"],
  33: ["e_p1_6", "e_p1_9", "e_p1_12"],
  34: ["e_p2_2"],
  35: ["e_p1_1", "e_p1_11", "e_p2_1"],
  36: ["e_p2_3"],
  37: ["e_p2_2", "e_p1_12", "e_p1_11"],
  38: ["e_p2_4"],
  39: ["e_p2_1", "e_p1_13", "e_p1_10"],
  40: ["e_p2_5"],
  41: ["e_p2_2", "e_p1_1", "e_p1_11"],
  42: ["e_p2_6"],
  43: ["e_p2_3", "e_p2_5", "e_p2_4"],
  44: ["e_p2_7"],
  45: ["e_p2_6", "e_p2_4", "e_p1_10"],
  46: ["e_p2_8"],
  47: ["e_p1_1", "e_p2_1", "e_p2_6"],
  48: ["e_p2_9"],
  49: ["e_p2_3", "e_p2_8", "e_p1_13"],
  50: ["e_p2_10"],
  51: ["e_p2_8", "e_p1_10", "e_p1_12"],
  52: ["e_p2_11"],
  53: ["e_p2_7", "e_p2_4", "e_p2_10"],
  54: ["e_p2_8", "e_p2_4"],
  55: ["e_p1_12", "e_p2_3", "e_p2_10"],
  56: ["e_p2_12"],
  57: ["e_p2_8", "e_p1_1", "e_p2_9"],
  58: ["e_p2_13"],
  59: ["e_p2_11", "e_p2_12", "e_p2_4"],
  60: ["e_p2_14"],
  61: ["e_p1_12", "e_p2_8", "e_p1_10"],
  62: ["e_p1_11", "e_p2_4"],
  63: ["e_p1_1", "e_p2_14", "e_p2_7"],
  64: ["e_p2_13", "e_p2_1"],
  65: ["e_p2_4", "e_p2_12", "e_p1_10"],
  66: ["e_p2_9", "e_p2_7"],
  67: ["e_p2_14", "e_p2_11", "e_p2_4"],
  68: ["e_p3_1"],
  69: ["e_p2_14", "e_p2_8", "e_p2_3"],
  70: ["e_p3_2"],
  71: ["e_p2_14", "e_p2_13", "e_p1_1"],
  72: ["e_p2_9", "e_p2_5"],
  73: ["e_p3_2", "e_p2_7", "e_p2_3"],
  74: ["e_p3_3"],
  75: ["e_p2_11", "e_p2_5", "e_p1_10"],
  76: ["e_p3_4"],
  77: ["e_p3_2", "e_p3_3", "e_p1_1"],
  78: ["e_p3_5"],
  79: ["e_p3_1", "e_p2_3", "e_p3_3"],
  80: ["e_p2_7", "e_p3_4"],
  81: ["e_p3_2", "e_p2_11", "e_p3_5"],
  82: ["e_p3_6"],
  83: ["e_p3_5", "e_p2_7", "e_p3_1"],
  84: ["e_p3_7"],
  85: ["e_p3_4", "e_p3_6", "e_p1_1"],
  86: ["e_p3_8"],
  87: ["e_p3_5", "e_p3_6", "e_p3_7"],
  88: ["e_p3_9"],
  89: ["e_p2_9", "e_p3_7", "e_p1_1"],
  90: ["e_p3_10"],
  91: ["e_p3_9", "e_p3_1", "e_p3_5"],
  92: ["e_p3_11"],
  93: ["e_p2_7", "e_p3_7", "e_p1_1"],
  94: ["e_p3_12"],
  95: ["e_p3_8", "e_p1_1", "e_p3_9"],
  96: ["e_p3_12", "e_p3_11", "e_p3_1"],
  97: ["e_p3_7", "e_p3_5"],
  98: ["e_p3_13"],
  99: ["e_p3_9", "e_p3_10", "e_p3_1"],
  100: ["e_p3_14"],
  101: ["e_p1_1", "e_p3_8", "e_p3_12"],
  102: ["e_p3_15"],
  103: ["e_p3_14", "e_p3_8", "e_p3_13"],
  104: ["e_p4_1"],
  105: ["e_p3_8", "e_p3_10", "e_p3_13"],
  106: ["e_p3_12", "e_p3_13", "e_p3_11"],
  107: ["e_p3_15", "e_p3_14"],
  108: ["e_p4_2"],
  109: ["e_p3_13", "e_p4_1", "e_p3_8"],
  110: ["e_p4_3"],
  111: ["e_p1_1", "e_p4_2", "e_p3_9"],
  112: ["e_p3_8", "e_p4_1"],
  113: ["e_p4_3", "e_p3_15", "e_p3_13"],
  114: ["e_p4_4"],
  115: ["e_p1_1", "e_p4_2", "e_p3_9"],
  116: ["e_p4_5"],
  117: ["e_p3_14", "e_p1_1", "e_p3_15"],
  118: ["e_p4_6"],
  119: ["e_p4_2", "e_p3_9", "e_p4_3"],
  120: ["e_p4_7"],
  121: ["e_p4_6", "e_p3_15", "e_p4_5"],
  122: ["e_p3_14", "e_p4_4"],
  123: ["e_p4_2", "e_p1_1", "e_p4_7"],
  124: ["e_p4_8"],
  125: ["e_p4_6", "e_p3_8", "e_p4_5"],
  126: ["e_p4_9"],
  127: ["e_p4_2", "e_p3_15", "e_p1_1"],
  128: ["e_p4_10"],
  129: ["e_p4_6", "e_p4_7", "e_p4_8"],
  130: ["e_p4_11"],
  131: ["e_p3_8", "e_p4_9", "e_p1_1"],
  132: ["e_p4_5", "e_p4_10"],
  133: ["e_p3_15", "e_p4_6", "e_p4_8"],
  134: ["e_p4_12"],
  135: ["e_p4_4", "e_p4_11", "e_p1_1"],
  136: ["e_p4_5", "e_p4_10"],
  137: ["e_p4_6", "e_p4_8", "e_p3_15"],
  138: ["e_p4_13"],
  139: ["e_p4_9", "e_p1_1", "e_p4_11"],
  140: ["e_p5_1"],
  141: ["e_p3_15", "e_p4_6", "e_p4_13"],
  142: ["e_p5_2"],
  143: ["e_p5_1", "e_p1_1", "e_p4_12"],
  144: ["e_p5_3"],
  145: ["e_p5_2", "e_p4_6", "e_p4_5"],
  146: ["e_p5_4"],
  147: ["e_p4_12", "e_p1_1", "e_p5_1"],
  148: ["e_p5_5"],
  149: ["e_p5_4", "e_p5_3", "e_p4_13"],
  150: ["e_p5_6"],
  151: ["e_p4_12", "e_p5_2", "e_p4_6"],
  152: ["e_p5_7"],
  153: ["e_p5_4", "e_p5_3", "e_p5_6"],
  154: ["e_p5_8"],
  155: ["e_p5_7", "e_p4_12", "e_p5_2"],
  156: ["e_p5_9"],
  157: ["e_p5_5", "e_p5_3", "e_p1_1"],
  158: ["e_p5_10"],
  159: ["e_p5_6", "e_p5_2", "e_p5_4"],
  160: ["e_p5_11"],
  161: ["e_p5_10", "e_p5_8", "e_p4_6"],
  162: ["e_p5_12"],
  163: ["e_p5_11", "e_p5_9"],
  164: ["e_p5_13"],
  165: ["e_p5_7", "e_p5_5", "e_p5_10"],
  166: ["e_p5_14"],
  167: ["e_p4_6", "e_p5_11", "e_p5_8"],
  168: ["e_p5_15"],
  169: ["e_p5_2", "e_p1_1", "e_p5_9"],
  170: ["e_p5_10", "e_p4_6", "e_p5_15"],
  171: ["e_p5_4", "e_p5_5", "e_p5_13"],
  172: ["e_p5_16"],
  173: ["e_p5_14", "e_p5_13", "e_p5_12"],
  174: ["e_p5_10", "e_p5_14", "e_p5_15"],
  175: ["e_p5_16", "e_p5_12"],
};

export const CLEO_WORKBOOK_PAGES = Object.keys(CLEO_WORKBOOK_PAGE_MAP)
  .map(Number)
  .sort((left, right) => left - right);

export const CLEO_WORKBOOK_EXERCISE_BY_ID = Object.fromEntries(
  CLEO_WORKBOOK_EXERCISES.map((exercise) => [exercise.id, exercise]),
) as Record<string, CleoWorkbookExercise>;
