import type { Session } from "@/lib/ardoise-data";

export const FIRST_SCHOOL_DAY_KEY = "2026-09-01";

export function createBoulardFirstSchoolDay(): Session[] {
  return [
    {
      id: "2026-09-01-accueil",
      start: "08:20",
      end: "08:30",
      title: "Accueil des élèves",
      subject: "rituels",
      free: true,
      note: "Accueil dans la cour, pointage et accompagnement vers la classe.",
    },
    {
      id: "2026-09-01-presentation",
      start: "08:30",
      end: "08:50",
      title: "Bienvenue en CE1",
      subject: "francais",
      pedagogicalDomain: "Langage oral",
      free: true,
      note: "Présentation de l'enseignant et de la classe. Tour de parole court : prénom et une chose aimée pendant les vacances.",
    },
    {
      id: "2026-09-01-installation",
      start: "08:50",
      end: "09:20",
      title: "Installation et matériel",
      subject: "emc",
      pedagogicalDomain: "Vivre ensemble",
      free: true,
      note: "Repérer sa place, ranger le matériel personnel, étiqueter les cahiers et présenter les règles essentielles de la classe.",
    },
    {
      id: "2026-09-01-ecriture",
      start: "09:20",
      end: "09:50",
      title: "Première page du cahier d'écriture",
      subject: "francais",
      pedagogicalDomain: "Écriture",
      free: true,
      note: "Copie guidée : « Aujourd'hui, c'est la rentrée. Je suis en CE1 dans la classe de M. Boulard. » Puis petit autoportrait illustré.",
    },
    {
      id: "2026-09-01-recreation-matin",
      start: "09:50",
      end: "10:05",
      title: "Récréation",
      subject: "pause",
      free: true,
    },
    {
      id: "2026-09-01-orthographemic-diagnostic",
      start: "10:05",
      end: "10:35",
      title: "Orthographémic : démarrage du diagnostic",
      subject: "francais",
      pedagogicalDomain: "Étude de la langue",
      free: true,
      programmingItemId: "ortho-s1",
      note: "Présenter le cadre rassurant, expliquer les consignes et réaliser la première partie du diagnostic. Recueillir des repères, sans correction collective ni notation annoncée.",
    },
    {
      id: "2026-09-01-maths-jeu",
      start: "10:35",
      end: "11:00",
      title: "Défis nombres en équipes",
      subject: "maths",
      pedagogicalDomain: "Nombres et calcul",
      free: true,
      note: "Jeu du furet puis courts défis coopératifs : ranger des nombres, compléter une suite et expliquer sa stratégie.",
    },
    {
      id: "2026-09-01-liaison",
      start: "11:00",
      end: "11:30",
      title: "Cahier de liaison et fonctionnement de la classe",
      subject: "emc",
      pedagogicalDomain: "Vivre ensemble",
      free: true,
      note: "Distribution du cahier de liaison, explication des documents à rapporter et des premiers repères de la journée.",
    },
    {
      id: "2026-09-01-pause",
      start: "11:30",
      end: "13:20",
      title: "Pause méridienne",
      subject: "pause",
      free: true,
    },
    {
      id: "2026-09-01-lecture",
      start: "13:20",
      end: "13:30",
      title: "Lecture offerte de rentrée",
      subject: "francais",
      pedagogicalDomain: "Lecture",
      free: true,
      note: "Lecture offerte d'un album de rentrée, puis échange libre sur les personnages et les émotions ressenties.",
    },
    {
      id: "2026-09-01-agenda",
      start: "13:30",
      end: "13:50",
      title: "Découverte de l'agenda",
      subject: "rituels",
      free: true,
      note: "Repérer le jour, la date et les devoirs. Première copie collective, guidée ligne par ligne.",
    },
    {
      id: "2026-09-01-production-ecrit",
      start: "13:50",
      end: "14:20",
      title: "Production d'écrit : ma carte de présentation",
      subject: "francais",
      pedagogicalDomain: "Écriture",
      builderTemplateId: "production-ecrit",
      free: true,
      note: "Écrire quelques mots ou phrases sur soi à partir d'amorces : « Je m'appelle... », « J'aime... », « Cette année, j'aimerais... ».",
    },
    {
      id: "2026-09-01-anglais",
      start: "14:20",
      end: "14:50",
      title: "Anglais : Hello, my name is...",
      subject: "lve",
      pedagogicalDomain: "Comprendre et s'exprimer à l'oral",
      free: true,
      note: "Rituel de salutation, présentation orale très courte et première chanson de nombres.",
    },
    {
      id: "2026-09-01-recreation-apres-midi",
      start: "14:50",
      end: "15:05",
      title: "Récréation",
      subject: "pause",
      free: true,
    },
    {
      id: "2026-09-01-arts",
      start: "15:05",
      end: "16:05",
      title: "Arts visuels : étiquette de porte-manteau",
      subject: "arts",
      pedagogicalDomain: "Arts plastiques",
      free: true,
      note: "Créer une étiquette personnelle lisible avec son prénom et un dessin qui permet de se reconnaître.",
    },
    {
      id: "2026-09-01-poesie",
      start: "16:05",
      end: "16:30",
      title: "Poésie et préparation du cartable",
      subject: "francais",
      pedagogicalDomain: "Langage oral",
      free: true,
      note: "Découverte d'une courte poésie de rentrée, puis rangement guidé du cartable et rappel des documents à rapporter.",
    },
  ];
}
