import type { Session } from "@/lib/ardoise-data";

export const FIRST_SCHOOL_DAY_KEY = "2026-09-01";

export function createBoulardFirstSchoolDay(): Session[] {
  return [
    {
      id: "2026-09-01-accueil",
      start: "08:20",
      end: "08:30",
      title: "Accueil des élèves",
      subject: "rituels",
      free: true,
      note: "Accueil dans la cour, pointage et accompagnement vers la classe.",
    },
    {
      id: "2026-09-01-presentation",
      start: "08:30",
      end: "08:50",
      title: "Bienvenue en CE1 : jeu pour apprendre à se connaître",
      subject: "francais",
      pedagogicalDomain: "Langage oral",
      prepSheetId: "prep-rentree-presentation",
      resourceId: "rentree-presentation",
      note: "Présentation de l'enseignant et de la classe, puis jeu en petits groupes avec les cartes « premier contact » : vacances, passion, activité préférée, jour préféré ou objet de la trousse.",
    },
    {
      id: "2026-09-01-installation",
      start: "08:50",
      end: "09:20",
      title: "Installation, matériel et coloriage autonome",
      subject: "emc",
      pedagogicalDomain: "Vivre ensemble",
      free: true,
      note: "Les élèves colorient calmement une fiche de rentrée pendant que l'enseignant vérifie, élève par élève, le matériel et les affaires. Puis repérer sa place, ranger le matériel personnel et étiqueter les cahiers.",
    },
    {
      id: "2026-09-01-ecriture",
      start: "09:20",
      end: "09:50",
      title: "Cahier de dictée : présentation et première phrase",
      subject: "francais",
      pedagogicalDomain: "Écriture",
      prepSheetId: "prep-rentree-dictee",
      resourceId: "rentree-dictee",
      note: "Présenter le code du cahier : compter un carreau, sauter une ligne, commencer une nouvelle ligne, barrer proprement et corriger en vert. Dictée de rentrée : « Aujourd'hui, c'est la rentrée. Je suis en CE1 D dans la classe de Monsieur Boulard. »",
    },
    {
      id: "2026-09-01-recreation-matin",
      start: "09:50",
      end: "10:05",
      title: "Récréation",
      subject: "pause",
      free: true,
    },
    {
      id: "2026-09-01-orthographemic-diagnostic",
      start: "10:05",
      end: "10:35",
      title: "Orthographémic : démarrage du diagnostic",
      subject: "francais",
      pedagogicalDomain: "Étude de la langue",
      programmingItemId: "ortho-s1",
      prepSheetId: "prep-rentree-ortho-diagnostic",
      resourceId: "rs-ortho-s1",
      note: "Présenter le cadre rassurant, expliquer les consignes et réaliser la première partie du diagnostic. Recueillir des repères, sans correction collective ni notation annoncée.",
    },
    {
      id: "2026-09-01-maths-jeu",
      start: "10:35",
      end: "10:50",
      title: "Jeu du furet",
      subject: "maths",
      pedagogicalDomain: "Nombres et calcul",
      prepSheetId: "prep-rentree-furet",
      resourceId: "rentree-furet",
      note: "Jeu oral collectif : compter de 1 en 1 puis de 2 en 2. Installer une dynamique de groupe avant la courte évaluation diagnostique.",
    },
    {
      id: "2026-09-01-maths-diagnostic",
      start: "10:50",
      end: "11:30",
      title: "Mathématiques : évaluation diagnostique - nombres de 1 à 99",
      subject: "maths",
      pedagogicalDomain: "Nombres et calcul",
      prepSheetId: "prep-rentree-maths-diagnostic",
      resourceId: "rentree-maths-diagnostic",
      note: "Courte évaluation diagnostique : lire, écrire, ranger et comparer des nombres de 1 à 99. Ramasser les productions pour observer les besoins, sans correction collective.",
    },
    {
      id: "2026-09-01-pause",
      start: "11:30",
      end: "13:20",
      title: "Pause méridienne",
      subject: "pause",
      free: true,
    },
    {
      id: "2026-09-01-date",
      start: "13:20",
      end: "13:30",
      title: "Rituel de la date",
      subject: "rituels",
      free: true,
      note: "Retour au calme, repérage du jour, de la date et du programme de l'après-midi.",
    },
    {
      id: "2026-09-01-quart-heure-lecture",
      start: "13:30",
      end: "13:45",
      title: "Quart d'heure de lecture",
      subject: "francais",
      pedagogicalDomain: "Lecture",
      free: true,
      note: "Temps calme de lecture autonome. L'enseignant aide à choisir un livre et observe l'entrée dans l'activité.",
    },
    {
      id: "2026-09-01-agenda",
      start: "13:45",
      end: "14:05",
      title: "Présentation de l'agenda et copie des devoirs",
      subject: "rituels",
      prepSheetId: "prep-rentree-agenda",
      resourceId: "rentree-agenda",
      note: "Repérer le jour et la date, présenter les rubriques de l'agenda puis copier les devoirs collectivement, ligne par ligne.",
    },
    {
      id: "2026-09-01-lecture-comprehension",
      start: "14:05",
      end: "14:50",
      title: "Lecture compréhension : C'est la rentrée...",
      subject: "francais",
      pedagogicalDomain: "Lecture et compréhension de l'écrit",
      prepSheetId: "prep-rentree-lecture-comprehension",
      resourceId: "rentree-lecture-comprehension",
      note: "Fiche de compréhension « C'est la rentrée... » transmise. Lire, répondre aux questions, puis revenir sur les stratégies de compréhension.",
    },
    {
      id: "2026-09-01-recreation-apres-midi",
      start: "14:50",
      end: "15:05",
      title: "Récréation",
      subject: "pause",
      free: true,
    },
    {
      id: "2026-09-01-liaison",
      start: "15:05",
      end: "15:30",
      title: "Cahier de liaison et papiers à compléter",
      subject: "emc",
      pedagogicalDomain: "Vivre ensemble",
      prepSheetId: "prep-rentree-liaison",
      resourceId: "rentree-liaison",
      note: "Distribution du cahier de liaison et des documents de rentrée. Expliquer ce qui doit être complété et signé à la maison.",
    },
    {
      id: "2026-09-01-poesie",
      start: "15:30",
      end: "16:00",
      subject: "francais",
      pedagogicalDomain: "Langage oral",
      prepSheetId: "prep-rentree-poesie",
      resourceId: "rentree-poesie",
      title: "Poésie : Vive la rentrée !",
      note: "Découverte de « Vive la rentrée ! » de Karine Persillet : lecture expressive, compréhension et premiers vers à mémoriser.",
    },
    {
      id: "2026-09-01-illustration-poesie",
      start: "16:00",
      end: "16:20",
      title: "Illustration de la poésie",
      subject: "arts",
      pedagogicalDomain: "Arts plastiques",
      prepSheetId: "prep-rentree-illustration",
      resourceId: "rentree-illustration",
      note: "Illustrer un vers ou une image de la poésie avec soin. Le travail sera poursuivi un autre jour si nécessaire.",
    },
    {
      id: "2026-09-01-cartable",
      start: "16:20",
      end: "16:30",
      title: "Préparation du cartable",
      subject: "rituels",
      free: true,
      note: "Rangement guidé. Devoirs pour demain : compléter et faire signer le cahier de liaison, rapporter les fiches de renseignements remplies et revoir la poésie.",
    },
  ];
}
