import type { PrepSheet, ResourceMethod } from "@/lib/ardoise-data";

export const FIRST_SCHOOL_DAY_PREP_SHEETS: PrepSheet[] = [
  {
    id: "prep-rentree-presentation",
    title: "Bienvenue en CE1 : apprendre à se connaître",
    subject: "francais",
    objective: "Installer un climat de classe serein et permettre à chacun de prendre la parole.",
    competence: "Écouter les autres et s'exprimer clairement dans un échange collectif.",
    duration: "20 min",
    phases: [
      { title: "Accueil en cercle", duration: "5 min", detail: "Présenter l'enseignant, la classe et les deux règles du jeu : écouter et laisser chacun finir sa réponse." },
      { title: "Cartes premier contact", duration: "10 min", detail: "Faire circuler les cartes : vacances, passion, activité préférée, jour préféré ou objet de la trousse. Chaque élève répond à une question simple." },
      { title: "Bilan", duration: "5 min", detail: "Faire reformuler quelques prénoms et découvertes pour commencer à mémoriser le groupe." },
    ],
    material: ["Cartes « premier contact »", "Étiquettes-prénoms si nécessaire"],
    photocopies: [],
  },
  {
    id: "prep-rentree-dictee",
    title: "Cahier de dictée : présentation et première phrase",
    subject: "francais",
    objective: "Installer les gestes de présentation du cahier et écrire une première phrase collective avec soin.",
    competence: "Copier et écrire une phrase courte en respectant l'organisation de la page.",
    duration: "30 min",
    phases: [
      { title: "Observation du code", duration: "8 min", detail: "Projeter la fiche de présentation. Faire expliciter : compter un carreau, sauter une ligne, commencer une nouvelle ligne, barrer à la règle et corriger en vert." },
      { title: "Installation dans le cahier", duration: "7 min", detail: "Distribuer le cahier de dictée, repérer la première page et préparer la date avec les élèves." },
      { title: "Phrase de rentrée", duration: "10 min", detail: "Dicter lentement puis relire par groupes de mots : « Aujourd'hui, c'est la rentrée. Je suis en CE1 D dans la classe de Monsieur Boulard. »" },
      { title: "Relecture guidée", duration: "5 min", detail: "Vérifier collectivement majuscule, apostrophe, point et présentation. Valoriser le soin plutôt que la vitesse." },
    ],
    material: ["Cahier de dictée", "Fiche de présentation des cahiers projetée au rétroprojecteur ou au TNI", "Rétroprojecteur ou TNI", "Crayon à papier, règle et stylo vert"],
    photocopies: ["Fiche de présentation des cahiers : 1 exemplaire à projeter"],
    notes: ["La fiche de présentation transmise sert de modèle visuel pendant toute la séance."],
  },
  {
    id: "prep-rentree-ortho-diagnostic",
    title: "Orthographémic CE1 : évaluations diagnostiques",
    subject: "francais",
    objective: "Recueillir des premiers repères en lecture et orthographe sans mettre les élèves en difficulté.",
    competence: "Mobiliser ses premières connaissances du code et de l'orthographe.",
    duration: "30 min",
    phases: [
      { title: "Cadre rassurant", duration: "5 min", detail: "Présenter l'activité comme un point de départ pour aider chacun, sans note ni comparaison entre élèves." },
      { title: "Passation guidée", duration: "20 min", detail: "Distribuer le dossier Orthographémic déjà imprimé. Lire chaque consigne, vérifier la compréhension, puis laisser le temps de répondre individuellement." },
      { title: "Collecte", duration: "5 min", detail: "Ramasser les dossiers sans correction collective. Noter les élèves qui ont besoin d'une passation plus accompagnée." },
    ],
    material: ["Dossier élève « Mes évaluations diagnostiques » Orthographémic CE1", "Crayons à papier", "Gomme"],
    photocopies: ["Évaluations diagnostiques Orthographémic CE1 : 10 exemplaires déjà imprimés"],
    notes: ["Cette séance est rattachée à Orthographémic CE1, semaine 1. Elle ne renvoie à aucune page d'exercices du manuel."],
  },
  {
    id: "prep-rentree-furet",
    title: "Jeu du furet : compter ensemble",
    subject: "maths",
    objective: "Réactiver oralement la suite numérique et observer la participation de chacun.",
    competence: "Dire, lire et utiliser les nombres entiers.",
    duration: "15 min",
    phases: [
      { title: "Compter de 1 en 1", duration: "7 min", detail: "Lancer un premier tour jusqu'à 30. Garder un rythme lent et reprendre sereinement lorsqu'un élève hésite." },
      { title: "Varier le départ", duration: "5 min", detail: "Repartir d'un nombre annoncé, puis proposer un second tour de 2 en 2 selon le groupe." },
      { title: "Bilan", duration: "3 min", detail: "Faire verbaliser que la suite des nombres aide à trouver le nombre suivant." },
    ],
    material: ["Aucun matériel spécifique"],
    photocopies: [],
  },
  {
    id: "prep-rentree-maths-diagnostic",
    title: "Évaluation diagnostique CE1 : nombres de 1 à 99",
    subject: "maths",
    objective: "Repérer les acquis sur la lecture, l'écriture, le rangement et la comparaison des nombres de 1 à 99.",
    competence: "Utiliser et comparer les nombres entiers inférieurs à 100.",
    duration: "40 min",
    phases: [
      { title: "Consignes", duration: "5 min", detail: "Présenter la feuille comme un outil pour connaître les besoins de la classe. Lire les consignes une à une." },
      { title: "Recherche individuelle", duration: "30 min", detail: "Laisser les élèves avancer à leur rythme. Observer discrètement les procédures et proposer une reformulation des consignes sans donner de réponse." },
      { title: "Ramassage", duration: "5 min", detail: "Ramasser les évaluations pour préparer les premiers groupes de besoin. Aucune correction collective aujourd'hui." },
    ],
    material: ["Évaluations diagnostiques CE1 de mathématiques", "Crayons à papier", "Gommes"],
    photocopies: ["Évaluations diagnostiques CE1 - mathématiques : 10 exemplaires déjà imprimés"],
    notes: ["Aucune référence à la page 34 : elle ne correspond pas à cette évaluation diagnostique."],
  },
  {
    id: "prep-rentree-agenda",
    title: "Présentation de l'agenda et copie des devoirs",
    subject: "rituels",
    objective: "Comprendre l'organisation de l'agenda et copier les devoirs de façon autonome et lisible.",
    competence: "Se repérer dans le temps et utiliser un outil d'organisation.",
    duration: "20 min",
    phases: [
      { title: "Repères dans l'agenda", duration: "8 min", detail: "Montrer la date, les jours de la semaine et l'emplacement des devoirs. Faire retrouver le lendemain." },
      { title: "Copie guidée", duration: "10 min", detail: "Copier les devoirs collectivement, ligne par ligne. Vérifier la présentation avant de poursuivre." },
      { title: "Vérification", duration: "2 min", detail: "Faire relire avec le voisin puis ranger l'agenda dans le cartable." },
    ],
    material: ["Agenda de chaque élève", "Modèle des devoirs au tableau ou projeté"],
    photocopies: [],
  },
  {
    id: "prep-rentree-lecture-comprehension",
    title: "Lecture compréhension : C'est la rentrée...",
    subject: "francais",
    objective: "Lire un texte de rentrée et répondre à des questions de compréhension explicite.",
    competence: "Lire et comprendre un texte adapté à son âge.",
    duration: "45 min",
    phases: [
      { title: "Découverte du texte", duration: "10 min", detail: "Observer le titre et les personnages. Lire le texte à voix haute une première fois, puis faire relever le contexte de la rentrée." },
      { title: "Lecture et questions", duration: "25 min", detail: "Distribuer la fiche « C'est la rentrée... ». Lire les consignes, laisser les élèves répondre, puis accompagner les lecteurs fragiles en petit groupe." },
      { title: "Retour sur le texte", duration: "10 min", detail: "Revenir sur quelques réponses avec le texte sous les yeux. Valoriser les stratégies : chercher l'information, relire, justifier." },
    ],
    material: ["Fiche de lecture compréhension « C'est la rentrée... »", "Crayons à papier", "Surligneurs facultatifs"],
    photocopies: ["Fiche « C'est la rentrée... » : 10 exemplaires à prévoir"],
    notes: ["Support transmis en PDF. Il remplace toute référence erronée à une page d'exercices."],
  },
  {
    id: "prep-rentree-liaison",
    title: "Cahier de liaison et documents de rentrée",
    subject: "emc",
    objective: "Comprendre le rôle du cahier de liaison et identifier les documents à faire compléter à la maison.",
    competence: "Respecter les règles de la vie collective et communiquer avec les familles.",
    duration: "25 min",
    phases: [
      { title: "Présentation", duration: "8 min", detail: "Montrer les rubriques du cahier de liaison et expliquer qu'il circule entre l'école et la famille." },
      { title: "Distribution", duration: "12 min", detail: "Distribuer les cahiers et les documents. Faire ranger chaque feuille dans le bon ordre." },
      { title: "Consigne maison", duration: "5 min", detail: "Faire entourer ce qui doit être complété ou signé et rappeler où ranger le cahier." },
    ],
    material: ["Cahier de liaison", "Papiers de rentrée à compléter", "Étiquettes si nécessaires"],
    photocopies: ["Documents de rentrée : 1 jeu par élève"],
  },
  {
    id: "prep-rentree-poesie",
    title: "Poésie : Vive la rentrée !",
    subject: "francais",
    objective: "Découvrir une poésie de rentrée, comprendre son thème et mémoriser les premiers vers.",
    competence: "Dire de mémoire un texte court en respectant le rythme et l'intonation.",
    duration: "20 min",
    phases: [
      { title: "Lecture expressive", duration: "5 min", detail: "Lire « Vive la rentrée ! » de Karine Persillet avec une intonation expressive. Laisser un temps de réaction." },
      { title: "Compréhension", duration: "7 min", detail: "Faire relever les images de la rentrée : vacances, cartables, nouvelle classe, découvertes." },
      { title: "Mémorisation", duration: "8 min", detail: "Dire collectivement le premier passage par écho. Annoncer que la poésie sera revue à la maison." },
    ],
    material: ["Poésie « Vive la rentrée ! » de Karine Persillet", "Affichage ou projection de la poésie"],
    photocopies: ["Poésie : 1 exemplaire par élève"],
  },
  {
    id: "prep-rentree-illustration",
    title: "Illustration de la poésie de rentrée",
    subject: "arts",
    objective: "Choisir une image de la poésie et la représenter avec soin.",
    competence: "Expérimenter et produire une création plastique personnelle.",
    duration: "25 min",
    phases: [
      { title: "Choix de l'image", duration: "5 min", detail: "Relire les vers et choisir une image à représenter : cartable, nouvelle classe ou découvertes." },
      { title: "Réalisation", duration: "17 min", detail: "Dessiner puis colorier soigneusement. Accompagner le choix des outils sans imposer de modèle." },
      { title: "Rangement", duration: "3 min", detail: "Signer le travail, ranger les outils et glisser la poésie dans le cahier prévu." },
    ],
    material: ["Crayons de couleur", "Feutres", "Poésie distribuée"],
    photocopies: [],
  },
];

export function getFirstSchoolDayPrepSheet(id?: string): PrepSheet | undefined {
  return FIRST_SCHOOL_DAY_PREP_SHEETS.find((sheet) => sheet.id === id);
}

export const FIRST_SCHOOL_DAY_RESOURCE_METHOD: ResourceMethod = {
  id: "m-rentree-ce1",
  label: "Rentrée CE1 — premières séances",
  subject: "francais",
  sequences: [
    {
      id: "s-rentree-matin",
      label: "Matin",
      sessions: [
        { id: "rentree-presentation", label: "Bienvenue en CE1 : apprendre à se connaître", prepSheetId: "prep-rentree-presentation" },
        { id: "rentree-dictee", label: "Présentation du cahier de dictée", prepSheetId: "prep-rentree-dictee" },
        { id: "rs-ortho-s1", label: "Orthographémic CE1 — Évaluations diagnostiques", prepSheetId: "prep-rentree-ortho-diagnostic" },
        { id: "rentree-furet", label: "Jeu du furet : compter ensemble", prepSheetId: "prep-rentree-furet" },
        { id: "rentree-maths-diagnostic", label: "Évaluation diagnostique : nombres de 1 à 99", prepSheetId: "prep-rentree-maths-diagnostic" },
      ],
    },
    {
      id: "s-rentree-apres-midi",
      label: "Après-midi",
      sessions: [
        { id: "rentree-agenda", label: "Présentation de l'agenda et devoirs", prepSheetId: "prep-rentree-agenda" },
        { id: "rentree-lecture-comprehension", label: "Lecture compréhension : C'est la rentrée...", prepSheetId: "prep-rentree-lecture-comprehension" },
        { id: "rentree-liaison", label: "Cahier de liaison et documents", prepSheetId: "prep-rentree-liaison" },
        { id: "rentree-poesie", label: "Poésie : Vive la rentrée !", prepSheetId: "prep-rentree-poesie" },
        { id: "rentree-illustration", label: "Illustration de la poésie", prepSheetId: "prep-rentree-illustration" },
      ],
    },
  ],
};
