export type ImportedWritingProgrammingSequence = {
  order: number;
  id: string;
  group: string;
  title: string;
  currentWorkbookPages: number[];
  teacherPages: number[];
  legacyWorkbookPages: number[];
  sourceStatus: "aligned" | "partial" | "summary_only";
  updateNeeded: boolean;
};

export type ImportedWritingAnnualProgramming = {
  method: string;
  subject: string;
  level: string;
  sourceGuidePdfPages: number[];
  sourceSummaryImage: string;
  note: string;
  sequences: ImportedWritingProgrammingSequence[];
};

export const mdiEcritureTransitionProgramming = {
  method: "Mes cahiers d'écriture Laurence Pierson — Perfectionnement, les minuscules",
  subject: "Écriture",
  level: "CP / CE1",
  sourceGuidePdfPages: [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
  ],
  sourceSummaryImage: "/Users/lohanboulard/Desktop/Capture d’écran 2026-08-08 à 11.15.24.png",
  note: "Programmation cible structurée d'après le nouveau sommaire 2025/2026 fourni par capture. Les contenus détaillés proviennent du guide pédagogique 2018 quand la correspondance est disponible ; le reste est laissé à [À VÉRIFIER] pour mise à jour ultérieure.",
  sequences: [
    {
      order: 1,
      id: "mdi-ecriture-transition-position-corps-avant-bras",
      group: "Avant d'écrire",
      title: "La position du corps et de l'avant-bras",
      currentWorkbookPages: [4],
      teacherPages: [4, 5],
      legacyWorkbookPages: [4, 5],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 2,
      id: "mdi-ecriture-transition-tenue-crayon",
      group: "Avant d'écrire",
      title: "La tenue du crayon",
      currentWorkbookPages: [5],
      teacherPages: [4, 5],
      legacyWorkbookPages: [4, 5],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 3,
      id: "mdi-ecriture-transition-entrainement-pouce",
      group: "Avant d'écrire",
      title: "L'entraînement du pouce",
      currentWorkbookPages: [6, 7],
      teacherPages: [4, 5],
      legacyWorkbookPages: [4, 5],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 4,
      id: "mdi-ecriture-transition-deplacement-avant-bras",
      group: "Avant d'écrire",
      title: "Le déplacement de l'avant-bras",
      currentWorkbookPages: [8, 9],
      teacherPages: [5],
      legacyWorkbookPages: [5],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 5,
      id: "mdi-ecriture-transition-formes-de-base",
      group: "Avant d'écrire",
      title: "Les formes de base",
      currentWorkbookPages: [10, 11],
      teacherPages: [2],
      legacyWorkbookPages: [],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 6,
      id: "mdi-ecriture-transition-lettres-e-l",
      group: "L'écriture des lettres",
      title: "Les lettres e et l",
      currentWorkbookPages: [12, 13],
      teacherPages: [8, 9],
      legacyWorkbookPages: [6, 7],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 7,
      id: "mdi-ecriture-transition-lettres-i-u-t",
      group: "L'écriture des lettres",
      title: "Les lettres i, u, t",
      currentWorkbookPages: [14, 15],
      teacherPages: [10],
      legacyWorkbookPages: [8, 9],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 8,
      id: "mdi-ecriture-transition-lettres-c-a-d-o",
      group: "L'écriture des lettres",
      title: "Les lettres c, a, d, o",
      currentWorkbookPages: [16, 17],
      teacherPages: [11],
      legacyWorkbookPages: [10, 11],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 9,
      id: "mdi-ecriture-transition-lettres-m-n-p",
      group: "L'écriture des lettres",
      title: "Les lettres m, n, p",
      currentWorkbookPages: [18, 19],
      teacherPages: [12],
      legacyWorkbookPages: [12, 13],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 10,
      id: "mdi-ecriture-transition-lettres-r-s",
      group: "L'écriture des lettres",
      title: "Les lettres r et s",
      currentWorkbookPages: [20, 21],
      teacherPages: [13, 14],
      legacyWorkbookPages: [14, 15, 16, 17],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 11,
      id: "mdi-ecriture-transition-lettres-h-k",
      group: "L'écriture des lettres",
      title: "Les lettres h et k",
      currentWorkbookPages: [22, 23],
      teacherPages: [15],
      legacyWorkbookPages: [18, 19],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 12,
      id: "mdi-ecriture-transition-lettre-f",
      group: "L'écriture des lettres",
      title: "La lettre f",
      currentWorkbookPages: [24, 25],
      teacherPages: [16],
      legacyWorkbookPages: [20, 21],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 13,
      id: "mdi-ecriture-transition-lettres-j-y-g-q",
      group: "L'écriture des lettres",
      title: "Les lettres j, y, g, q",
      currentWorkbookPages: [26, 27],
      teacherPages: [17, 18],
      legacyWorkbookPages: [22, 23, 24, 25],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 14,
      id: "mdi-ecriture-transition-lettres-b-v-w",
      group: "L'écriture des lettres",
      title: "Les lettres b, v, w",
      currentWorkbookPages: [28, 29],
      teacherPages: [19],
      legacyWorkbookPages: [26, 27],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 15,
      id: "mdi-ecriture-transition-lettres-z-x",
      group: "L'écriture des lettres",
      title: "Les lettres z et x",
      currentWorkbookPages: [30, 31],
      teacherPages: [20, 21],
      legacyWorkbookPages: [28, 29, 30, 31],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 16,
      id: "mdi-ecriture-transition-lettres-c-oe",
      group: "L'écriture des lettres",
      title: "Les lettres ç et œ",
      currentWorkbookPages: [32, 33],
      teacherPages: [22],
      legacyWorkbookPages: [32, 33],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 17,
      id: "mdi-ecriture-transition-enchainements",
      group: "L'écriture des lettres",
      title: "Les enchaînements",
      currentWorkbookPages: [34, 35],
      teacherPages: [13, 19],
      legacyWorkbookPages: [],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 18,
      id: "mdi-ecriture-transition-ponctuation",
      group: "Consolidation",
      title: "La ponctuation",
      currentWorkbookPages: [36, 37],
      teacherPages: [23],
      legacyWorkbookPages: [34, 35, 36, 37, 38],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 19,
      id: "mdi-ecriture-transition-utilisation-regle",
      group: "Consolidation",
      title: "L'utilisation de la règle",
      currentWorkbookPages: [38, 39],
      teacherPages: [24],
      legacyWorkbookPages: [42, 43],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 20,
      id: "mdi-ecriture-transition-ecriture-chiffres",
      group: "Consolidation",
      title: "L'écriture des chiffres",
      currentWorkbookPages: [40, 41],
      teacherPages: [24],
      legacyWorkbookPages: [44, 45, 46, 47],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
    {
      order: 21,
      id: "mdi-ecriture-transition-copie-couleurs",
      group: "Stratégies de copie",
      title: "Copie en couleurs",
      currentWorkbookPages: [42, 43],
      teacherPages: [],
      legacyWorkbookPages: [],
      sourceStatus: "summary_only",
      updateNeeded: true,
    },
    {
      order: 22,
      id: "mdi-ecriture-transition-copie-distance",
      group: "Stratégies de copie",
      title: "Copie à distance",
      currentWorkbookPages: [44, 45],
      teacherPages: [],
      legacyWorkbookPages: [],
      sourceStatus: "summary_only",
      updateNeeded: true,
    },
    {
      order: 23,
      id: "mdi-ecriture-transition-vers-ecriture-courante",
      group: "Stratégies de copie",
      title: "Vers l'écriture courante",
      currentWorkbookPages: [46, 47],
      teacherPages: [23],
      legacyWorkbookPages: [38, 39, 40, 41],
      sourceStatus: "partial",
      updateNeeded: true,
    },
    {
      order: 24,
      id: "mdi-ecriture-transition-copie-poeme",
      group: "Stratégies de copie",
      title: "Copie d'un poème",
      currentWorkbookPages: [48],
      teacherPages: [25],
      legacyWorkbookPages: [48],
      sourceStatus: "aligned",
      updateNeeded: false,
    },
  ],
} as const satisfies ImportedWritingAnnualProgramming;
