/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AteliersRepriseRouteImport } from './routes/ateliers-reprise'
import { Route as BilanSeanceRouteImport } from './routes/bilan-seance'
import { Route as CarnetNotesRouteImport } from './routes/carnet-notes'
import { Route as CompagnonClasseRouteImport } from './routes/compagnon-classe'
import { Route as CorrectionRapideRouteImport } from './routes/correction-rapide'
import { Route as ElevesRouteImport } from './routes/eleves'
import { Route as EmploiDuTempsRouteImport } from './routes/emploi-du-temps'
import { Route as FluenceRouteImport } from './routes/fluence'
import { Route as GroupesBesoinRouteImport } from './routes/groupes-besoin'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagerieRouteImport } from './routes/messagerie'
import { Route as ProgrammationRouteImport } from './routes/programmation'
import { Route as ProgrammationAnnuelleRouteImport } from './routes/programmation-annuelle'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as ResultatsExercicesRouteImport } from './routes/resultats-exercices'
import { Route as ApiAiPedagogicalAssistantRouteImport } from './routes/api/ai/pedagogical-assistant'
import { Route as ApiAiPlumeJournalRouteImport } from './routes/api/ai/plume-journal'
import { Route as ApiAiSessionPlanRouteImport } from './routes/api/ai/session-plan'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiCalendarEventsRouteImport } from './routes/api/calendar/events'
import { Route as ApiMailN8nRouteImport } from './routes/api/mail/n8n'
import { Route as ApiCalendarGoogleCallbackRouteImport } from './routes/api/calendar/google/callback'
import { Route as ApiCalendarGoogleConnectRouteImport } from './routes/api/calendar/google/connect'
import { Route as ApiCalendarGoogleStatusRouteImport } from './routes/api/calendar/google/status'
import { Route as ApiCalendarIcloudEventsRouteImport } from './routes/api/calendar/icloud/events'
import { Route as ApiIntegrationsN8nMailRouteImport } from './routes/api/integrations/n8n/mail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AteliersRepriseRoute = AteliersRepriseRouteImport.update({
  id: '/ateliers-reprise',
  path: '/ateliers-reprise',
  getParentRoute: () => rootRouteImport,
} as any)
const BilanSeanceRoute = BilanSeanceRouteImport.update({
  id: '/bilan-seance',
  path: '/bilan-seance',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetNotesRoute = CarnetNotesRouteImport.update({
  id: '/carnet-notes',
  path: '/carnet-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompagnonClasseRoute = CompagnonClasseRouteImport.update({
  id: '/compagnon-classe',
  path: '/compagnon-classe',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionRapideRoute = CorrectionRapideRouteImport.update({
  id: '/correction-rapide',
  path: '/correction-rapide',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesRoute = ElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploiDuTempsRoute = EmploiDuTempsRouteImport.update({
  id: '/emploi-du-temps',
  path: '/emploi-du-temps',
  getParentRoute: () => rootRouteImport,
} as any)
const FluenceRoute = FluenceRouteImport.update({
  id: '/fluence',
  path: '/fluence',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesBesoinRoute = GroupesBesoinRouteImport.update({
  id: '/groupes-besoin',
  path: '/groupes-besoin',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagerieRoute = MessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammationRoute = ProgrammationRouteImport.update({
  id: '/programmation',
  path: '/programmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammationAnnuelleRoute = ProgrammationAnnuelleRouteImport.update({
  id: '/programmation-annuelle',
  path: '/programmation-annuelle',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsExercicesRoute = ResultatsExercicesRouteImport.update({
  id: '/resultats-exercices',
  path: '/resultats-exercices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPedagogicalAssistantRoute =
  ApiAiPedagogicalAssistantRouteImport.update({
    id: '/api/ai/pedagogical-assistant',
    path: '/api/ai/pedagogical-assistant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiPlumeJournalRoute = ApiAiPlumeJournalRouteImport.update({
  id: '/api/ai/plume-journal',
  path: '/api/ai/plume-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSessionPlanRoute = ApiAiSessionPlanRouteImport.update({
  id: '/api/ai/session-plan',
  path: '/api/ai/session-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarEventsRoute = ApiCalendarEventsRouteImport.update({
  id: '/api/calendar/events',
  path: '/api/calendar/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailN8nRoute = ApiMailN8nRouteImport.update({
  id: '/api/mail/n8n',
  path: '/api/mail/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarGoogleCallbackRoute =
  ApiCalendarGoogleCallbackRouteImport.update({
    id: '/api/calendar/google/callback',
    path: '/api/calendar/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalendarGoogleConnectRoute =
  ApiCalendarGoogleConnectRouteImport.update({
    id: '/api/calendar/google/connect',
    path: '/api/calendar/google/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalendarGoogleStatusRoute = ApiCalendarGoogleStatusRouteImport.update({
  id: '/api/calendar/google/status',
  path: '/api/calendar/google/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarIcloudEventsRoute = ApiCalendarIcloudEventsRouteImport.update({
  id: '/api/calendar/icloud/events',
  path: '/api/calendar/icloud/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsN8nMailRoute = ApiIntegrationsN8nMailRouteImport.update({
  id: '/api/integrations/n8n/mail',
  path: '/api/integrations/n8n/mail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ateliers-reprise': typeof AteliersRepriseRoute
  '/bilan-seance': typeof BilanSeanceRoute
  '/carnet-notes': typeof CarnetNotesRoute
  '/compagnon-classe': typeof CompagnonClasseRoute
  '/correction-rapide': typeof CorrectionRapideRoute
  '/eleves': typeof ElevesRoute
  '/emploi-du-temps': typeof EmploiDuTempsRoute
  '/fluence': typeof FluenceRoute
  '/groupes-besoin': typeof GroupesBesoinRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/messagerie': typeof MessagerieRoute
  '/programmation': typeof ProgrammationRoute
  '/programmation-annuelle': typeof ProgrammationAnnuelleRoute
  '/ressources': typeof RessourcesRoute
  '/resultats-exercices': typeof ResultatsExercicesRoute
  '/api/ai/pedagogical-assistant': typeof ApiAiPedagogicalAssistantRoute
  '/api/ai/plume-journal': typeof ApiAiPlumeJournalRoute
  '/api/ai/session-plan': typeof ApiAiSessionPlanRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/mail/n8n': typeof ApiMailN8nRoute
  '/api/calendar/google/callback': typeof ApiCalendarGoogleCallbackRoute
  '/api/calendar/google/connect': typeof ApiCalendarGoogleConnectRoute
  '/api/calendar/google/status': typeof ApiCalendarGoogleStatusRoute
  '/api/calendar/icloud/events': typeof ApiCalendarIcloudEventsRoute
  '/api/integrations/n8n/mail': typeof ApiIntegrationsN8nMailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ateliers-reprise': typeof AteliersRepriseRoute
  '/bilan-seance': typeof BilanSeanceRoute
  '/carnet-notes': typeof CarnetNotesRoute
  '/compagnon-classe': typeof CompagnonClasseRoute
  '/correction-rapide': typeof CorrectionRapideRoute
  '/eleves': typeof ElevesRoute
  '/emploi-du-temps': typeof EmploiDuTempsRoute
  '/fluence': typeof FluenceRoute
  '/groupes-besoin': typeof GroupesBesoinRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/messagerie': typeof MessagerieRoute
  '/programmation': typeof ProgrammationRoute
  '/programmation-annuelle': typeof ProgrammationAnnuelleRoute
  '/ressources': typeof RessourcesRoute
  '/resultats-exercices': typeof ResultatsExercicesRoute
  '/api/ai/pedagogical-assistant': typeof ApiAiPedagogicalAssistantRoute
  '/api/ai/plume-journal': typeof ApiAiPlumeJournalRoute
  '/api/ai/session-plan': typeof ApiAiSessionPlanRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/mail/n8n': typeof ApiMailN8nRoute
  '/api/calendar/google/callback': typeof ApiCalendarGoogleCallbackRoute
  '/api/calendar/google/connect': typeof ApiCalendarGoogleConnectRoute
  '/api/calendar/google/status': typeof ApiCalendarGoogleStatusRoute
  '/api/calendar/icloud/events': typeof ApiCalendarIcloudEventsRoute
  '/api/integrations/n8n/mail': typeof ApiIntegrationsN8nMailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ateliers-reprise': typeof AteliersRepriseRoute
  '/bilan-seance': typeof BilanSeanceRoute
  '/carnet-notes': typeof CarnetNotesRoute
  '/compagnon-classe': typeof CompagnonClasseRoute
  '/correction-rapide': typeof CorrectionRapideRoute
  '/eleves': typeof ElevesRoute
  '/emploi-du-temps': typeof EmploiDuTempsRoute
  '/fluence': typeof FluenceRoute
  '/groupes-besoin': typeof GroupesBesoinRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/messagerie': typeof MessagerieRoute
  '/programmation': typeof ProgrammationRoute
  '/programmation-annuelle': typeof ProgrammationAnnuelleRoute
  '/ressources': typeof RessourcesRoute
  '/resultats-exercices': typeof ResultatsExercicesRoute
  '/api/ai/pedagogical-assistant': typeof ApiAiPedagogicalAssistantRoute
  '/api/ai/plume-journal': typeof ApiAiPlumeJournalRoute
  '/api/ai/session-plan': typeof ApiAiSessionPlanRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/mail/n8n': typeof ApiMailN8nRoute
  '/api/calendar/google/callback': typeof ApiCalendarGoogleCallbackRoute
  '/api/calendar/google/connect': typeof ApiCalendarGoogleConnectRoute
  '/api/calendar/google/status': typeof ApiCalendarGoogleStatusRoute
  '/api/calendar/icloud/events': typeof ApiCalendarIcloudEventsRoute
  '/api/integrations/n8n/mail': typeof ApiIntegrationsN8nMailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/ateliers-reprise'
    | '/bilan-seance'
    | '/carnet-notes'
    | '/compagnon-classe'
    | '/correction-rapide'
    | '/eleves'
    | '/emploi-du-temps'
    | '/fluence'
    | '/groupes-besoin'
    | '/journal'
    | '/login'
    | '/messagerie'
    | '/programmation'
    | '/programmation-annuelle'
    | '/ressources'
    | '/resultats-exercices'
    | '/api/ai/pedagogical-assistant'
    | '/api/ai/plume-journal'
    | '/api/ai/session-plan'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/calendar/events'
    | '/api/mail/n8n'
    | '/api/calendar/google/callback'
    | '/api/calendar/google/connect'
    | '/api/calendar/google/status'
    | '/api/calendar/icloud/events'
    | '/api/integrations/n8n/mail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/ateliers-reprise'
    | '/bilan-seance'
    | '/carnet-notes'
    | '/compagnon-classe'
    | '/correction-rapide'
    | '/eleves'
    | '/emploi-du-temps'
    | '/fluence'
    | '/groupes-besoin'
    | '/journal'
    | '/login'
    | '/messagerie'
    | '/programmation'
    | '/programmation-annuelle'
    | '/ressources'
    | '/resultats-exercices'
    | '/api/ai/pedagogical-assistant'
    | '/api/ai/plume-journal'
    | '/api/ai/session-plan'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/calendar/events'
    | '/api/mail/n8n'
    | '/api/calendar/google/callback'
    | '/api/calendar/google/connect'
    | '/api/calendar/google/status'
    | '/api/calendar/icloud/events'
    | '/api/integrations/n8n/mail'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/ateliers-reprise'
    | '/bilan-seance'
    | '/carnet-notes'
    | '/compagnon-classe'
    | '/correction-rapide'
    | '/eleves'
    | '/emploi-du-temps'
    | '/fluence'
    | '/groupes-besoin'
    | '/journal'
    | '/login'
    | '/messagerie'
    | '/programmation'
    | '/programmation-annuelle'
    | '/ressources'
    | '/resultats-exercices'
    | '/api/ai/pedagogical-assistant'
    | '/api/ai/plume-journal'
    | '/api/ai/session-plan'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/calendar/events'
    | '/api/mail/n8n'
    | '/api/calendar/google/callback'
    | '/api/calendar/google/connect'
    | '/api/calendar/google/status'
    | '/api/calendar/icloud/events'
    | '/api/integrations/n8n/mail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AteliersRepriseRoute: typeof AteliersRepriseRoute
  BilanSeanceRoute: typeof BilanSeanceRoute
  CarnetNotesRoute: typeof CarnetNotesRoute
  CompagnonClasseRoute: typeof CompagnonClasseRoute
  CorrectionRapideRoute: typeof CorrectionRapideRoute
  ElevesRoute: typeof ElevesRoute
  EmploiDuTempsRoute: typeof EmploiDuTempsRoute
  FluenceRoute: typeof FluenceRoute
  GroupesBesoinRoute: typeof GroupesBesoinRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  MessagerieRoute: typeof MessagerieRoute
  ProgrammationRoute: typeof ProgrammationRoute
  ProgrammationAnnuelleRoute: typeof ProgrammationAnnuelleRoute
  RessourcesRoute: typeof RessourcesRoute
  ResultatsExercicesRoute: typeof ResultatsExercicesRoute
  ApiAiPedagogicalAssistantRoute: typeof ApiAiPedagogicalAssistantRoute
  ApiAiPlumeJournalRoute: typeof ApiAiPlumeJournalRoute
  ApiAiSessionPlanRoute: typeof ApiAiSessionPlanRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiCalendarEventsRoute: typeof ApiCalendarEventsRoute
  ApiMailN8nRoute: typeof ApiMailN8nRoute
  ApiCalendarGoogleCallbackRoute: typeof ApiCalendarGoogleCallbackRoute
  ApiCalendarGoogleConnectRoute: typeof ApiCalendarGoogleConnectRoute
  ApiCalendarGoogleStatusRoute: typeof ApiCalendarGoogleStatusRoute
  ApiCalendarIcloudEventsRoute: typeof ApiCalendarIcloudEventsRoute
  ApiIntegrationsN8nMailRoute: typeof ApiIntegrationsN8nMailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ateliers-reprise': {
      id: '/ateliers-reprise'
      path: '/ateliers-reprise'
      fullPath: '/ateliers-reprise'
      preLoaderRoute: typeof AteliersRepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilan-seance': {
      id: '/bilan-seance'
      path: '/bilan-seance'
      fullPath: '/bilan-seance'
      preLoaderRoute: typeof BilanSeanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnet-notes': {
      id: '/carnet-notes'
      path: '/carnet-notes'
      fullPath: '/carnet-notes'
      preLoaderRoute: typeof CarnetNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compagnon-classe': {
      id: '/compagnon-classe'
      path: '/compagnon-classe'
      fullPath: '/compagnon-classe'
      preLoaderRoute: typeof CompagnonClasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correction-rapide': {
      id: '/correction-rapide'
      path: '/correction-rapide'
      fullPath: '/correction-rapide'
      preLoaderRoute: typeof CorrectionRapideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves': {
      id: '/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof ElevesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emploi-du-temps': {
      id: '/emploi-du-temps'
      path: '/emploi-du-temps'
      fullPath: '/emploi-du-temps'
      preLoaderRoute: typeof EmploiDuTempsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluence': {
      id: '/fluence'
      path: '/fluence'
      fullPath: '/fluence'
      preLoaderRoute: typeof FluenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes-besoin': {
      id: '/groupes-besoin'
      path: '/groupes-besoin'
      fullPath: '/groupes-besoin'
      preLoaderRoute: typeof GroupesBesoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messagerie': {
      id: '/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof MessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmation': {
      id: '/programmation'
      path: '/programmation'
      fullPath: '/programmation'
      preLoaderRoute: typeof ProgrammationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmation-annuelle': {
      id: '/programmation-annuelle'
      path: '/programmation-annuelle'
      fullPath: '/programmation-annuelle'
      preLoaderRoute: typeof ProgrammationAnnuelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats-exercices': {
      id: '/resultats-exercices'
      path: '/resultats-exercices'
      fullPath: '/resultats-exercices'
      preLoaderRoute: typeof ResultatsExercicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/pedagogical-assistant': {
      id: '/api/ai/pedagogical-assistant'
      path: '/api/ai/pedagogical-assistant'
      fullPath: '/api/ai/pedagogical-assistant'
      preLoaderRoute: typeof ApiAiPedagogicalAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/plume-journal': {
      id: '/api/ai/plume-journal'
      path: '/api/ai/plume-journal'
      fullPath: '/api/ai/plume-journal'
      preLoaderRoute: typeof ApiAiPlumeJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/session-plan': {
      id: '/api/ai/session-plan'
      path: '/api/ai/session-plan'
      fullPath: '/api/ai/session-plan'
      preLoaderRoute: typeof ApiAiSessionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/events': {
      id: '/api/calendar/events'
      path: '/api/calendar/events'
      fullPath: '/api/calendar/events'
      preLoaderRoute: typeof ApiCalendarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/n8n': {
      id: '/api/mail/n8n'
      path: '/api/mail/n8n'
      fullPath: '/api/mail/n8n'
      preLoaderRoute: typeof ApiMailN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/google/callback': {
      id: '/api/calendar/google/callback'
      path: '/api/calendar/google/callback'
      fullPath: '/api/calendar/google/callback'
      preLoaderRoute: typeof ApiCalendarGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/google/connect': {
      id: '/api/calendar/google/connect'
      path: '/api/calendar/google/connect'
      fullPath: '/api/calendar/google/connect'
      preLoaderRoute: typeof ApiCalendarGoogleConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/google/status': {
      id: '/api/calendar/google/status'
      path: '/api/calendar/google/status'
      fullPath: '/api/calendar/google/status'
      preLoaderRoute: typeof ApiCalendarGoogleStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/icloud/events': {
      id: '/api/calendar/icloud/events'
      path: '/api/calendar/icloud/events'
      fullPath: '/api/calendar/icloud/events'
      preLoaderRoute: typeof ApiCalendarIcloudEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/n8n/mail': {
      id: '/api/integrations/n8n/mail'
      path: '/api/integrations/n8n/mail'
      fullPath: '/api/integrations/n8n/mail'
      preLoaderRoute: typeof ApiIntegrationsN8nMailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AteliersRepriseRoute: AteliersRepriseRoute,
  BilanSeanceRoute: BilanSeanceRoute,
  CarnetNotesRoute: CarnetNotesRoute,
  CompagnonClasseRoute: CompagnonClasseRoute,
  CorrectionRapideRoute: CorrectionRapideRoute,
  ElevesRoute: ElevesRoute,
  EmploiDuTempsRoute: EmploiDuTempsRoute,
  FluenceRoute: FluenceRoute,
  GroupesBesoinRoute: GroupesBesoinRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  MessagerieRoute: MessagerieRoute,
  ProgrammationRoute: ProgrammationRoute,
  ProgrammationAnnuelleRoute: ProgrammationAnnuelleRoute,
  RessourcesRoute: RessourcesRoute,
  ResultatsExercicesRoute: ResultatsExercicesRoute,
  ApiAiPedagogicalAssistantRoute: ApiAiPedagogicalAssistantRoute,
  ApiAiPlumeJournalRoute: ApiAiPlumeJournalRoute,
  ApiAiSessionPlanRoute: ApiAiSessionPlanRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiCalendarEventsRoute: ApiCalendarEventsRoute,
  ApiMailN8nRoute: ApiMailN8nRoute,
  ApiCalendarGoogleCallbackRoute: ApiCalendarGoogleCallbackRoute,
  ApiCalendarGoogleConnectRoute: ApiCalendarGoogleConnectRoute,
  ApiCalendarGoogleStatusRoute: ApiCalendarGoogleStatusRoute,
  ApiCalendarIcloudEventsRoute: ApiCalendarIcloudEventsRoute,
  ApiIntegrationsN8nMailRoute: ApiIntegrationsN8nMailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
